<?php

use Illuminate\Database\Seeder;

class BrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $data = [
            'MEDICAM',
            'DOVE',
            'KODAK',
            'FREEMAN',
            'SUN',
            'ENERGIZER',
            'SMART COLLECTION',
            'CAKE',
            'VATIKA',
            'NIKE',
            'SIGNAL',
            'HIMANI',
            'SUNSILIK',
            'DOL',
            'CLEAR',
            'BOWL',
            'JOLEN',
            'BODY',
            'UDV',
            'FA',
            'WISDOM',
            'NONE',
            'AMERICAN GARDEN',
            'ENLIVEN',
            'WHILE',
            'OPEN',
            'NIVEA',
            'LOCK&LOCK',
            'ELMORE',
            'EMSA',
            'OLAY',
            'FRUCTIS',
            'PHOTO',
            'PHILIPS',
            'CHATTU',
            'CAMBRIDGE',
            'HAQUE PLANTER',
            'KODOMO',
            'AKG',
            'FRUITAMINS',
            'SCHICK',
            'BABY',
            'FRESH',
            'JAZEE',
            'LADIES',
            'COLGATE',
            'AQUAFRESH',
            'NUTRO',
            'FLORA',
            'DETTOL',
            'KIWI',
            'HARPIC',
            'CANDY',
            'CIF',
            'RIVAJ',
            'SCOTCH BRITE',
            'VEET',
            'DIMPLES',
            'POWER',
            'LUBNAS',
            'STAINER',
            'MY',
            'SUPER',
            'TEA',
            'GLADE',
            'MUG',
            'ELECTRO',
            'PANTY',
            'TRAMONTINA',
            'GLASS',
            'VASE',
            'KITCHEN',
            'BRA',
            'MAGIC',
            'SPONTEX',
            'KOMAX',
            'HP',
            'SITARA',
            'T-PUMP',
            'NATIONAL',
            'DZMZ',
            'DAVIDOFF',
            'HAIR',
            'DUST',
            'HINZ',
            'ADAM',
            'CANBEBE',
            'REVLON',
            'PEDIASURE',
            'SENSODYEN',
            'PEDIGREE',
            'CRESCO',
            'FERRY',
            'ADAMS',
            'BASIC',
            'MEZAN',
            'WALLS',
            'SEASONS',
            'BORCAM',
            'AROMA',
            'TANG',
            'CLEAN & CLEAR',
            'JOHNSOINS',
            'HOLLYWOOD',
            'COLOUR ME',
            'SAPIL',
            'RASASI',
            'BODY LUXURIES',
            'VATKA',
            'GLISS',
            'HEAD & SHOULDERS',
            'XHC',
            'MENU',
            'GLYSOLID',
            'NATURALIUM',
            'CLING',
            'DIAMOND',
            'NESTLE',
            'LIFE STYLE',
            'PLATE',
            'GILLETTE',
            'BEEDY',
            'TIGHTS',
            'VATANI',
            'APPLE',
            'BREAD',
            'SHIELD',
            'MODEL',
            'MELLOW',
            'VASELIEN',
            'SALMANS',
            'KROS',
            'HUDA BEAUTY',
            '7CF',
            'WD-40',
            'TABLE',
            'KYLIE',
            'STEEL',
            'DEL',
            'SHICK',
            'FORHANS',
            'BOLD',
            'UDY',
            'SHIRLEY',
            'ASTONISH',
            'CREST',
            'MCVITIES',
            'HOME',
            'SHEZAN',
            'KASHMIR',
            'KK',
            'ROYAL',
            'CHEF',
            'ALMARAI',
            'PRETTY',
            'DAWN',
            'NIGHT',
            'BIG BIRD',
            'DERMACOS',
            'BLESSO',
            'DURACELL',
            'BROOM',
            'TRAY',
            'WIPER',
            'SHALIS',
            'KL',
            'GATSBY',
            'SOFT',
            'LIFEBUOY',
            'VACUUM',
            'PANTENE',
            'ARMAF',
            'BAJAJ',
            'RICOLA',
            'DABAR',
            'RAINBOW',
            'SUFI',
            'GOOD MILK',
            'KINGTOX',
            'INSE',
            'LUCKY',
            'KITTY',
            'VIVANT',
            'GARNIER',
            'MAJINA',
            'WESTPOINT',
            'DENIM',
            'ANIL',
            'LDNIOEXTENSION+USB',
            'SHAN',
            'ACID',
            'CIGAR',
            'K',
            'LOREAL',
            'HEINZ',
            'POINEER',
            'PURE HEAVEN',
            'WATER',
            'SHANGRILA',
            'WALTHER',
            'FOOD',
            'SENCOR',
            'DOORPHONE',
            'NOVA',
            'PAMPERS',
            'COW&GATE',
            'LOMANI',
            'SCENERY',
            'DITTUS',
            'DUFRAIS',
            'SATELLITE',
            'PRESIDENT',
            'LYS',
            'PARODONTAX',
            'CHOKI',
            'ENGLISH',
            'NATUR',
            'JUG',
            'CLINIC PLUS',
            'LADY DIANA',
            'NYLE',
            'FLORMAR',
            'MR MUSCLE',
            'DURU',
            'DEMACOS',
            'FAIR & LOVELY',
            'HALEEB',
            'CUP',
            'CHIEF',
            'BECUTE',
            'PULSE',
            'MITCHELLS',
            'QARSHI',
            'BLANKET',
            'ELEGANT',
            'BEAUTY FORMULAS',
            'CASHEW',
            'SILVERINA',
            'FINESSE',
            'MARLBORO',
            'HEREVIN',
            'FAIRY',
            'BEAUTY',
            'SUGAR',
            'YOUNGS',
            'HERBAL ESSENCES',
            'DENZILI',
            'BILLI',
            'FELIX',
            'SOAP',
            'DUCK',
            'COBRA',
            'SHOW',
            'CARDAMUM',
            'AL-REHAB',
            'COTT N TERRY',
            'SECRET',
            'ARM',
            'MORPHE',
            'ANGRY',
            'LONDON',
            'FOGG',
            'EMAMI',
            'HUGO',
            'GUCCI',
            '212',
            'HOMAGE',
            'DAL',
            'NICOS',
            'BEST',
            'JAYENAMAZ',
            'ENCHANTEUR',
            'K&NS',
            'LAKINRE',
            'SUPRI',
            'KINZA',
            'CAR',
            'PRESTIGE',
            'WHITE',
            'HAPPY COW',
            'CREME',
            'SCHWQARZKOPF',
            'TWIST',
            'ME-O',
            'TAPAL',
            'LIPTON',
            'CLOCK',
            'ESKULIN',
            'BLACK CAT',
            'JOHNSONS',
            'FALAK',
            'FRUCTIC',
            'IGORA',
            'XINXING',
            'YINGZIYI',
            'CAMERA',
            'D Move Cap 200000IU',
            'HAPPY',
            'FARLIN',
            'RICHELL',
            'KNIFE',
            'HAJI',
            'TEENS',
            'SABROSO',
            'MATEY',
            'HOLYWOOD',
            'PUR',
            'JAR',
            'HARIBO',
            'DIVINE',
            'LAMIS',
            'SET WET',
            'YARDLEY',
            'HE',
            'COLOUR',
            'ANASTASIA',
            'WHITE GOLD',
            'ORAL-B',
            'FLOWER',
            'JEWELARY',
            'U-Check Nebulizer',
            'MORTEIN',
            'AMB',
            'Digital Blue Temp',
            'AXE',
            'RADOX',
            'MACLEANS',
            'IMPERIAL',
            'WHISKAS',
            'ORETO',
            'FIGARO',
            'KURKURAE',
            'MILLAC',
            'FNF',
            'AQUA',
            'KELLOGGS',
            'MEADOW',
            'SCHAR GLUTEN FREE',
            'BAR',
            'CAMISOL',
            'YC',
            'ARCHI',
            'UMBRELLA',
            'HERBAL',
            'PAK',
            'SWAT',
            'NESQUIK',
            'FRISKIES',
            'STUTE',
            'TITIZ',
            'THE',
            'COLUR',
            'DALDA',
            'DISNEY',
            'MOP',
            'APK',
            'KEUNE',
            'DOLCE',
            'MARC',
            'IPSA',
            'CHICHI',
            'LAYERR',
            'BRUT',
            'SURE',
            'AIR WICK',
            'FEBREZE',
            'OCEAN',
            'RICE',
            'MAYBELLINE',
            'JERGENS',
            'PSB',
            'ALWAYS',
            'DERMOVIVA',
            'TARK',
            'SCENTED',
            'JAZZ',
            'ALMOND',
            'CARPET',
            'BIC',
            'TREET',
            'HANGER',
            'DOOR',
            'COSMETIC',
            'BORO PLUS',
            'SINGLE',
            'PIERRE',
            'ECLAIRS',
            'HOTLCE',
            'HOHO',
            'ZONG',
            'MAQ',
            'DABUR',
            'SHE',
            'BOLERO',
            'MORINAGA',
            'FRAMESI',
            'BASKET',
            'FROZEN',
            'WBM',
            'BISKITOP',
            'QUAKER',
            'LUX',
            'JUNSUI',
            'HIMALAYA',
            'GODREJ',
            'BIOMIL',
            'ENFAMIL',
            'SMART',
            'ETERNAL',
            'CHIKO',
            'HAED',
            'ZINC',
            'TUB',
            'ICE',
            'ANIMALS',
            'FAMILIA',
            'HICO',
            'CADBURY',
            'CLASSIC',
            'VENISIA',
            'OPPO',
            'DATA',
            'ADIDAS',
            'AVENT',
            'SUIKONE',
            'VEGITABLE',
            'PEARL DROPS',
            'PIZZA&CHEESE',
            'BORGES',
            'BOB',
            'FRENCH',
            'GLAMOROUS',
            'COLOR',
            'MEASURING',
            'GRILL',
            'KADU',
            'MURREE',
            'CHAMISOL',
            'GRANARIA',
            'CHEMISOL',
            'GUARD',
            'AVENGERS',
            'MEDORA',
            'EDEN ROC',
            'PICCADELI',
            'SALT',
            'NEUTROGENA',
            'AMRIJ',
            'CHILDREN',
            'GENTS',
            'GALLIPOLI',
            'DOUBLE',
            'MARHABA',
            'LISTRINE',
            'KEY',
            'FIRIDI',
            'LOTION',
            'JUICE',
            'LUMINARC',
            'DMGM',
            'ETUDE',
            'AMERICAN',
            'SAMSUNG',
            'FAST',
            'PALMOLIVE',
            'STILLMANS',
            'DEWDROP',
            'MARIOS',
            'DORITOS',
            'NESCAFE',
            'TRESEMME',
            'TELEPHONE',
            'Beurell Stethoscope',
            'NOVA GOLD',
            'V Care B.P Dial',
            'STIVES',
            'WOKALI',
            'HOLLY',
            'CHERRY',
            'JUST',
            'MAX',
            'M.A.C',
            'PLEDGE',
            'ROLEX',
            'MARINEX',
            'JELLY',
            'STILL',
            'CROWN',
            'KERNELPOP',
            'WALKING',
            'EASY ON',
            'ACRYLIC',
            'CRUET',
            'BRUSH',
            'HARTLEYS',
            'OVALTINE',
            'PONDS',
            'FABIMILK',
            'DELICACY',
            'LUNCH',
            'TOWER',
            'SHEET',
            'SUREE',
            'GATE',
            'MAM LUV',
            'PIGEON',
            'MINITREE',
            'SAMRT',
            'PARACHUTE',
            'LACE',
            'ALEXANDER',
            'SONEX',
            'PERT PLUS',
            'JUST FOR MEN',
            'DIABLO',
            'TREND',
            'NURPUR',
            'CHOC',
            'COROLI',
            'PISTA',
            'MAKE',
            'CUTTING',
            'SASSO',
            'LAKME',
            'RS',
            'SYMPHONY',
            'EXTENSION',
            'FRESHMATE',
            'KEMEI',
            'EVERY',
            'PAKORA',
            'AMBI',
            'SPRINGFRESH',
            'JOHSONS',
            'COOKING',
            'TAJ',
            'MOTHERCARE',
            'BANAT',
            'HEMANI',
            'CHINA',
            'FEM',
            'LANGNESE',
            'REXONA',
            'VIVENZI',
            'DRY',
            'LORYS',
            'PUNJAB',
            'FIREFLY',
            'OIL',
            'DRUMY',
            'EVA',
            'COMFORT',
            'EXPRESS',
            'TISSUE',
            'LINDA',
            'COFFEE',
            'LORETO',
            'B&B',
            'UNIVERSAL',
            'VENEEZIA',
            'FRUIT',
            'LA BONITA',
            'PIERE',
            'FARM',
            'TECHNO',
            'URBAN',
            'XBC',
            'CAREX',
            'DEURON',
            'CANDEREL',
            'NEO',
            'ENSURE',
            'RIGENOL',
            'HOT',
            'AWEI',
            'GLAD',
            'SUPERSOFT',
            'ARDACAM',
            'MISS',
            'DONGA',
            'LYNX',
            'GOLDEN GIRL',
            'LAMP',
            'DISH',
            'CANDYLAND',
            'DASHING',
            'SHAKARGANJ',
            'PALMERS',
            'NATURES',
            'MON SALWA',
            'FRUIT TREE',
            'BALOON',
            'GIANT',
            'REGGIA',
            'SAYIL',
            'NAIR',
            'FREAMESI',
            'KARISMA',
            'FULLO',
            'MRC',
            'OLIVOLA',
            'LAYS',
            'CRESPO',
            'CHIZZPA',
            'CHARM',
            'MR',
            'SPLENDA',
            'ANINA',
            'Collar Perfect Soft',
            'Poly Sling (Adult)',
            'SURFEXCEL',
            'WRIST',
            'AL',
            'BABY WORLD',
            'MUMLOVE',
            'EURO',
            'LINDO',
            'RIKA',
            'THE SCENT',
            'GRIFFIN',
            'LEMON MAX',
            'VIM',
            'MY PERFUMES',
            'Nepafen Drop 5 ml',
            'PAK PURE',
            'DOMESTOS',
            'PUSH',
            'SPONNTEX',
            'ROBIN',
            'RABBIT',
            'HANDI',
            'LUDAO',
            'ROMANTIC',
            'SYLKIN',
            'PRINGLES',
            'COOPEX',
            'JEWLLERY',
            'VITAL',
            'MOBILE',
            'BATH',
            'AIRWICK',
            'RELAX',
            'NYX',
            'LIEBUOY',
            'SMINT',
            'AMIGO',
            'BELLA',
            'SELSUN',
            'BIO AMLA',
            'BUTTERFLY',
            'LILLY',
            'KIDS',
            'PALTA',
            'ROMOLI',
            'FRESH&WHITE',
            'SHAMPOO',
            'LU',
            'TIBET',
            'LERVIA',
            'MATE',
            'FAUJI',
            'FOOT',
            'NANDOS',
            'DIPITT',
            'CLUB',
            'IPHONE',
            'SCISSOR',
            'RAI',
            'GIFT',
            'ELENA',
            'NESCAFE GOLD',
            'SPIDER-MAN',
            'DALAN',
            'ALISHA',
            'AZZARO',
            'BALLOONS',
            'BOBBY',
            'CHILD',
            'COSTA',
            'MAMA',
            'CHOICE',
            'BRYLCREEM',
            'RASCAL',
            'A/G',
            'GLINT',
            'CANDLE',
            'FIG',
            'SHOUT',
            'TOWEL',
            'JONSON',
            'DECORATION',
            'PREMIUM CHOICE',
            'SUAVE',
            'U.S.POLO',
            'INFLUX',
            'ONO',
            'PANASONIC',
            'BLACK&DECKER',
            'DALLAS',
            'DOMEX',
            'WELLA',
            '5TH',
            'BURBERRY',
            'ALEYNA',
            'I',
            'MR.BURBERRY',
            'ADMIRAL',
            'PURINA',
            'SPOON',
            'FINGER',
            'DANISA',
            'CELEBRATE',
            'VO5',
            'BIO',
            'KERATIN',
            'DECIBEL COLLECTION',
            'KOTEX',
            'GOLDEN PERAL',
            'LABELLO',
            'KERNEL',
            'SUDOCREAM',
            'K.H',
            'PIPE',
            'PLEASURES',
            'YAEDLEY',
            'MOTHER',
            'NATURELLE',
            'PUCK',
            'KRAFT',
            'BEST DAY',
            'DINNER',
            'FORK',
            'CAIZHI',
            'PEARS',
            'ROOH AFZA',
            'DELMOND',
            'COCO',
            'INVITATION',
            'CUPS',
            'NESFRUTA',
            'DISNEP',
            'GARNIGR',
            'EGG',
            'ST.IVES',
            'KENYA',
            'SLIMARMOR',
            'WILD',
            'LISTERINE',
            'TROPICANA',
            'DP',
            'DISPOSABLE',
            'KAUSAR',
            'CARE',
            'TELENOR',
            'MARVEL',
            'ARIEL',
            'BAYGON',
            'Hilton',
            'GREEN FARM',
            'SIMPLY',
            'SIGNATURE',
            'RIVER',
            'SAMS',
            'KENTUCKY',
            'KENCO',
            'SACLA',
            'FRUITIEN',
            'LEANING',
            'JALWATRI',
            'CLEAN&CLEAR',
            'MAY',
            'DAYFRESH',
            'POWDER',
            'GALAXY',
            'CARRERA',
            'EVERYWOMAN',
            'WARE',
            'BIOKIPS',
            'TIFFANY',
            'CLOTH',
            'BRITANNIA',
            'MARSHMALLOW',
            'LORY',
            'MINNIE',
            'AL-FALAH',
            'DARK',
            'PURE',
            'LADY SPEED',
            'VERT',
            'AFSHAN',
            'ALARM',
            'CASMOL',
            'CHRISTINE',
            'AWA',
            'BONUS',
            'TIDE',
            'TWINKLE',
            'COASTER',
            'ASTACO',
            'ENDURA',
            'UNCLE',
            'MERC',
            'RIVAJI',
            'OLD SPICE',
            'BABY MAGIC',
            'PASABAHCE',
            'STANLEY PHARMA',
            'PETAL',
            'CLEAN',
            'REMY',
            'SALAD',
            'OPA',
            'COLD',
            'BLUE',
            'NIK',
            'FANTA',
            'CUTE PLUS',
            'COMPLAN',
            'DEEP HEAT',
            'ROMANCE',
            'CHASTITY',
            'SUBARU',
            'MOLFIX',
            'FOOG',
            'DOCTOR',
            'HIMALAYAN CHEF',
            'GURDAL',
            'SPICE',
            'HYGLOBAL',
            'PRIME',
            'ELEGANCE',
            'AMORAY',
            'DETANGLER',
            'Certeza Stethoscope (3002)',
            'Room Temp Plastic HTC -1',
            'MIRROR',
            'EVEREADAY',
            'CANOLIVE',
            'EVELINE',
            'W7',
            'GLASS OCEAN',
            'REMIA',
            'DONG',
            'MONSTER',
            'BIGEN',
            'MEIJI',
            'F-LAC',
            'PIZZA',
            'ENZO',
            'BABI MILD',
            'LAUNDRY',
            'SUCRAL',
            'TORCH',
            'DIVA',
            'HILAL',
            'ALPENLAC',
            'NUNU',
            'IRON',
            'JOHAN',
            'SENATOR',
            'SIMAX',
            'DUSTER',
            'PLASTIC',
            'HOPE',
            'FOREVER',
            'OREAL',
            'GEORGE',
            'TERRACOTTA',
            'MALEE',
            'VICTORIA',
            'WHIPY',
            'LEATHER',
            'MAKEOVER',
            'TOP',
            'SAFIR',
            'SYOSS',
            'LOCK',
            'INTERLOCK',
            'LOVELY',
            'CALIFORNIA',
            'LOORY',
            'FEEDING',
            'NICE',
            'OLPERS',
            'AL AMEERA',
            'GOLD',
            'POLO',
            'TOM',
            'NEOPHAR',
            'DELSEY',
            'G',
            'SURF',
            'LICHEN',
            'MAMA SITAS',
            'DJ',
            'KOLSON',
            'MARICOS',
            'BIOLUXE',
            'ACTIVE',
            'COOL & COOL',
            'MABU',
            'CALENDER',
            'REWIN',
            'PLAY',
            'WORKSHOP',
            'TESCO',
            'HUGGIED',
            'SYLVANA',
            'LUXURIES',
            'DUNHIL',
            'STLTH',
            'YUNG',
            'K K',
            'ROMOSS',
            'ALSHIFA',
            'STYLISH',
            'CRUSHED',
            'POLAC',
            'STATUE',
            'SWP',
            'KOSMIK',
            'YARDLELY',
            'BRITE',
            'RISALA',
            'LO',
            'MILK PACK',
            'AIR WAY',
            'CK',
            'JOOP',
            'KENETH',
            'LACTOGROW',
            'AHMA',
            'SH',
            'ASCENSION',
            'EPIC',
            'THURSTONS',
            'PEPSICO',
            'ROOM',
            'TWININGS',
            'AIZHILANG',
            'PRINGELS',
            'MUNDIAL',
            'WADI FOOD',
            'RUBIA',
            'SOFTLAN',
            'VANISH',
            'KONSUNG',
            'RICA',
            'AUDIONIC',
            'BRILLIANT',
            'IMPERIAL LEATHER',
            'COOL&COOL',
            'NILOYA',
            'BILTON',
            'SHAN&CO.',
            'KNORR',
            'WARDROBE',
            'SAEED GHANI',
            'SAFEGUARD',
            'ALPHA',
            'SENRI',
            'LATTAFA',
            'PLEASURE',
            'IMPERATOR',
            'THICKER',
            'CAMELION',
            'SHINAX',
            'STORM',
            'GRAINS',
            'SLAZENGER',
            'SOFTLINE',
            'SABALON',
            'JAMAL',
            'DESSINI',
            'DELITE',
            'SUNBEAM',
            'DURACELL-D',
            'YADGAR',
            'VEGETABLE',
            'FEELINGS',
            'IDENTITY',
            'WHIIZZ',
            'POTATO',
            'AMERICAN KUISINE',
            'DLAMI',
            'U',
            'NIGHTY',
            'KURKURE',
            'KURLEEZ',
            'CORNITOS',
            'PARTY',
            'BIGG',
            'CILLE',
            'Certiza Mercarial CR (2001)',
            'Poly Sling (Child)',
            'MUM LOVE',
            'DAY',
            'PEPSI',
            'FAIR',
            'ONION',
            'SWEET',
            'CORSODYL',
            'JAI',
            'CUTLERY',
            'GSK',
            'KING',
            'ZERO',
            'LACTENA',
            'BELLAKT',
            'DUSTBIN',
            'USHAS',
            'MAY CARE',
            'TAG',
            'TONICURVE',
            'MARQUIS',
            'ELASTIC',
            'Easy Care Stethoscope 3E',
            'COLGANTE',
            'DRUM',
            'SCRUB SHINE',
            'WEETABIX',
            'GOLDEN',
            'ELVAN',
            'FORMULA 1',
            'BELT',
            'IMMACULATE',
            'NEW',
            'SW',
            'BAKE PARLOR',
            'HAQ',
            'REMINGTON',
            'SWEETEX',
            'BIG',
            'GUARDEX',
            'HDTV',
            'DIKSON',
            'SPORTS',
            'MATCHLESS',
            'CHANEL',
            'YOUNG\'S',
            'TRANING',
            'NESVITA',
            'DAIRY PURE',
            'OLIVE',
            'LEGEND',
            'KISS',
            'GETZ',
            'BANANA',
            'MEAT',
            'BOBBI',
            'EL',
            'CUFFLINKS',
            'CUFFLINK',
            'EZ',
            'BALTI',
            'NEXTON',
            'OPIO',
            'BOYU',
            'HAVOC',
            'INCIDENCE',
            'BETTY',
            'LOLANE',
            'JOVEN',
            'NUZZER',
            'DANCE',
            'IDEAL',
            'DELMONTE',
            'SIMILAC',
            'NAKED',
            'WESTPOIN',
            'EAZICOLOR',
            'STAR',
            'BEADS',
            'FUN',
            'TURTLE',
            'NAWAR',
            'ROLLER',
            'ECLIPSE',
            'FINO',
            'JAGUAR',
            'PREDO',
            'BLACK ROSE',
            'HASHMI',
            'TONI & GUY',
            'RISEN',
            'NUGHTY',
            'ROUND',
            'AIR',
            'EVER',
            'CHARLIE',
            'EAZI PLEX',
            'LE VOGUE',
            'NUDE',
            'PRONUBEN',
            'LIP',
            'MATILDE',
            'ASINEZ',
            'WELLAFLEX',
            'GLATT',
            'FINE',
            'THAI',
            'SHANI',
            'MONT',
            'VERSACE',
            'DELIGHT',
            'SEXY',
            'X-OVER',
            'FARERO',
            'PLAYBOY',
            'MAMIA',
            'SILVER',
            'ZAFA',
            'COOL WATER',
            'OSSIDORR',
            'FREASH',
            'GLUCERNA',
            'PANTEEN',
            'ALA',
            'CUSSONS',
            'ROOH AL ARAB',
            'MCCAIN',
            'PROFI',
            'ELECTRONIC',
            'ALPENIAC',
            'SISTEMA',
            'MITCHEELS',
            'SHIUXING',
            'FERRARI',
            'SANDS',
            'OBSESSION',
            'ECHO',
            'NEST',
            'LUBNA',
            'MONAMISE',
            'REX',
            'BLAK',
            'CARTIER',
            'LUSTER',
            'ARABIYAT TAJ',
            'CHCH',
            'BIOCOS',
            'SMA',
            'EXTRA',
            'DREAM',
            'JIOA',
            'RIMMEL',
            'Ezegut Probiotic Drop 5 ml',
            'BOURJOIS',
            'SHELLEY',
            'ITALIANO',
            'DR.RASHEL',
            'HIBAS',
            'ZANDU',
            'S',
            'HAUT NOTCH',
            'AIYO',
            'MINI',
            'JIAAI',
            'FASMC',
            'GAENIER',
            'TUFF',
            'WOK',
            'FIABILA',
            'Collar Perfect hard',
            'CHASE',
            'SENIOR',
            'ZIPLOC',
            'SHELLY',
            'ECO',
            'CHEF ONE',
            'SILVO',
            'Adapco fort gel 15 gm',
            'SERAMICS',
            'BRAUN',
            'AIRWAVES',
            'HANDEL',
            'LINKA',
            'HOMIO',
            'BROW',
            'DODIE',
            'CHISTINE',
            'ESSENCE',
            'FUJI',
            'OLD STYLE',
            'IT',
            'BEAUTE',
            'DINGLING',
            'HOPES',
            'PEPSODENT',
            'NIDO',
            'PROTEX',
            'EVLIYA',
            'TASBEEH',
            'INNOCENCE',
            'COLLAPSIBLE',
            'OMEGA',
            'PERFECT',
            'SIVANNA',
            'NICKY',
            'MAGNUM',
            'VIRGINIA',
            'KESH KING',
            'ASHTRAY',
            'Optium Free Style Meter',
            'OMO',
            'HELLO',
            'IGORAL',
            'ONE MAN SHOW',
            'SAHARA',
            'FINIS',
            'BOURN',
            'MINISTAR',
            'ELENI',
            'RIIFFS',
            'DAIRY',
            'HAIR CARE',
            'TECHNOPLAST',
            'FHOTO',
            'EHRAAM',
            'DR.JAMES',
            'GRASS',
            'CERAMIC',
            'PIONEER',
            'METAL',
            'TODDAY',
            'ROSE PETAL',
            'ORLANDO',
            'NSON',
            'SUPREME',
            'G-CASE',
            'KUNRI',
            'OLAZ',
            'JAKE',
            'ZAFRAN',
            'SMART TOUCH',
            'FOLDING',
            'GRINDER',
            'JB',
            'BASEUS',
            'MORTIEN',
            'TODDY',
            'WHINE',
            'MALAPINE',
            'ASTOR',
            'VOYAGER',
            'HAICHAO',
            'AL ARBIA',
            'AIM',
            'INSULATED',
            'VERAGE',
            'HOUSTON',
            '4U2',
            'HORLICKS',
            'ENVIRO',
            'OREO',
            'GOURMET',
            'WINE',
            'PRAYER',
            'VIGOS',
            'OXO',
            'ALDIVA',
            'DR.OETKER',
            'COCO ROYAL',
            'SOCKET',
            'LED',
            'ELEIN',
            'IVY',
            'SANIPLAST',
            'AMRICA',
            'LAP',
            'FAIZA',
            'ATHENA',
            'BLOO',
            'THARMOS',
            'CHIQUE',
            'MILK FIELDS',
            'JELLY BELLY',
            'BPGART',
            'SENSODINE',
            'PEEK FREANS',
            'SHOE',
            'SWAN',
            'DENUM',
            'MASTER KIDS',
            'HANNAS',
            'CLEAN & CLEAN',
            'KRYLON',
            'Biofreez gel 60 ml',
            'VERI VERI',
            'MORPHEXJACLYNHILL',
            'MOVE',
            'KHALIS',
            'TOMAS',
            'WOHU',
            'CREATIVE',
            'LACTOGEN',
            'ORANGE',
            'TOKRA',
            'NABIL',
            'SKITTLES',
            'ANTI',
            'CHOPSTICKS',
            'KSM',
            'SAMSOL',
            'TOUCHME',
            'MICKEY',
            'PATISSERIE',
            'LIGHTER',
            'PASABHACE',
            'OSSUM',
            'A',
            'Certeza Dial CR (1002)',
            'D Move Drop 20 ml',
            'KLIM',
            'BIRTHDAY',
            'SOFIA',
            'MILO',
            'VIRGINA',
            'INFINITE',
            'INSURRECTION',
            'BEARING',
            'DZMZDOUBLE',
            'SCHOOL',
            'EMBORG',
            'GOLDEN PEARL',
            'EAZI CARE',
            'SCREW',
            'ROCHE',
            'DAISY',
            'ACQUA DI PARISIS',
            'ROMEGA',
            'OSAKA',
            'ROSAE',
            'PILLOW',
            'CORAINDER',
            'GOLDENPEARL',
            'LASSI',
            '4ME',
            'KETTLE',
            'BBAY',
            'HAND',
            'FACE FRESH',
            'SAROO',
            'SEALWARE',
            'MUNDAL',
            'ORCHID',
            'CHIMTA',
            'SPANISH',
            'TAQWA',
            'BATCHELORS',
            'REYANE',
            'GARLIC',
            'PHARMEVO',
            'ENFAGROW',
            'TIE',
            'SONY',
            'MEETHI',
            'CBC',
            'PAPIA',
            'COOKIE',
            'REVEAL',
            'ARAMIS',
            'MAYBBELINE',
            'EMERGENCY',
            'FRAME',
            'PISTACHIO',
            'LIGHT',
            'UNEEK',
            'ACNES',
            'CHAOBA',
            'MODERNS',
            'STYLE',
            'AL-GHAZAAL',
            'GENNY',
            'AL-SHAMS',
            'HOSE',
            'WD40',
            'EAGLE',
            'MARYLAND',
            'BELINI',
            'NUTELLA',
            'MASTER',
            'TITI',
            'BRACKET',
            'HANSA',
            'DAVID',
            'CFP',
            'BUTTER',
            'RACK',
            'COTT N COLOR',
            'TRIDENT',
            'MOZER',
            'FRESHLE',
            'BISCONNI',
            'MILK',
            'WITE ROSE',
            'JUICER',
            'SILIS',
            'MENTOS',
            'NATURE',
            'EMOTION',
            'PEPPER',
            'BASE',
            'GULLON',
            'LISBONNE',
            'GLASSLOCK',
            'NANO',
            'KLEEYO',
            'KARO',
            'HANDS',
            'MASALA',
            'A.G',
            'TRUST',
            'TRAVEL',
            '7UP',
            'QURAN',
            'HEAVEN DOVE',
            'KOSEM',
            'MONCHY',
            'DADI',
            'BREAD & BEYOND',
            'KARAHI',
            'KIMIO',
            'MAYBEELINE',
            'SABAYA',
            'BETTY CROCKER',
            'BLANKIT',
            'MAXI',
            'GREEN WORLD',
            'NUTRAFIL',
            'BPA',
            'PHYSIOGEL',
            'POTTY',
            'HELLO HAIR',
            'MONSALWA',
            'BEST-ONE',
            'FADE OUT',
            'EUPHORIA',
            'Sizer 5 inch',
            'CC Clever Check B.P Wrist',
            'SOFT LINE',
            'DELUXE',
            'PRITECH',
            'MAMA LUV',
            'REMINGOTN',
            'SPRINGLEY',
            'ST',
            'GEMEI',
            'DUNHILL',
            'NAMKINO',
            'GENTLEMEN',
            'JOHN ALLEN',
            'RCR',
            'SESA',
            'TONY',
            'TIMOTEI',
            'KENZOKINO',
            'UNFORGIVABLE',
            'CAMAL',
            'HUAYU',
            'HERSHEYS',
            'EROS',
            'BONE',
            'TEA TREE',
            'BEST CHOICE',
            'ABAYA',
            'M2',
            'WHISPER',
            'MIGLIOR GATTO',
            'DERBY',
            'DAWLANCE',
            'SOBU',
            'HASAN',
            'TRACK',
            'VALENTINA',
            'KRYOLAN',
            'LIFEBOUY',
            'MAK',
            'WOOD',
            'STAY',
            'RIN',
            'AYSEMIN',
            'SNAPPLE',
            'MASALAH',
            'SANCY',
            'STORAGE',
            'PAINDOO PRODUCT',
            'ANYTIME',
            'ORVER',
            'MELOR',
            'FREDDI',
            'SCHAUMA',
            'PACO',
            'FASHION',
            'NOTE',
            'SUPER STORM',
            'BUGHY',
            'LOTTE',
            'EU',
            'GLAMOURS',
            'LION',
            'KIDDER & KIDDER',
            'CANPED',
            'SHOWER',
            'MY COOK',
            'IMMENSITY',
            'PHYSIOSEL',
            'SKIN WHITE',
            'SAF',
            'COCA COLA',
            'LUXURY',
            'FINI',
            'FRESHRITE',
            'GERBER',
            'DECLARATION',
            'KOUROS',
            'JOHN WEST',
            'BROWNS',
            'SOLECASA',
            'REEM',
            'FISHER',
            'DERMA SHINE',
            'FRUITTELLA',
            'TUTU',
            'LAVENNA',
            'GILLETE',
            'FABRIC',
            'BAKE TIME',
            'CONSENSUAL',
            'DARCO',
            'UNITED',
            'des chef',
            'VERSAILLES',
            'VINEGAR',
            'KARAT',
            'SECAN',
            'CASUALITE',
            'REACH',
            'SAMI',
            'SO',
            'BREMOD',
            'EVERYDAY',
            'THINBY',
            'LARK',
            'LALOREL',
            'GIGGLY',
            'COOKANIA',
            'JLW',
            'LACOSTE',
            'ANEX',
            'KSB',
            'ALYA',
            'KLASSNO',
            'COW',
            'ONCE',
            'SHAVER',
            'FARM FRESH',
            'BAIMEI',
            'DIY',
            'FOXS',
            'FLAVIA',
            'EZIGRIP',
            'ARBELLA',
            'SPINDLE',
            'PRODUCT',
            'D&G',
            'GUERLAIN',
            'OPAL',
            'VERY',
            'BLESS',
            'DIRHAM',
            'ANEE',
            'OVAL',
            'FRUIT-TELLA',
            'LOTUS',
            'HAQUE',
            'CHASTER',
            'MARGON',
            'CAPRI',
            'PERECT',
            'COMBINED',
            'FASCINO',
            'ROOT',
            'PES',
            'CARNAUBA',
            'DELESOL',
            'ALEDA',
            'SIENA',
            'BROOK',
            'MASTELA',
            'SUNRIDGE',
            'DR.MAGIC',
            'ICING',
            'PERT',
            'CLOROX',
            'OFOOD',
            'LIVELY',
            'QUALITY',
            'LUCARIS',
            'KATO',
            'SKINCARE',
            'BABI',
            'PROPHECY',
            'Calcium-p 400+D Tab',
            'SMILE',
            'HAFIZ',
            'ENGNUO',
            'AMSONS',
            'SPRITE',
            'TONY&GUY',
            'SALSA',
            'CORNER',
            'YENIINCI',
            'CO.E',
            'MARS',
            'AMOREENA',
            'ROSEPAIR',
            'SOFT TOUCH',
            'OLIVIA',
            'HABA\'S',
            'TAVERNA',
            'STYLING',
            'ULTREX',
            'TULSI',
            'MELAMINE',
            'MARANDA',
            'DERMA CLEAR',
            'MODEX',
            'WOOLITE',
            'MOUNTAIN',
            'PAKOLA',
            'VIMTO',
            'MICO',
            'FILIPPO BEIRO',
            'FRUTASIA',
            'NANNY',
            'MEAOON',
            'NURSA',
            'GLITTER',
            'PASIFIC',
            'CARINE',
            'HAMDARD',
            'ISSEY',
            'SAFARI',
            'CHANCE',
            'MARESI',
            'HARMONY',
            'DOMESTO',
            'BIDOU',
            'FEYZA',
            'NATURAL',
            'STUDY',
            'PURITY PLUS',
            'WINDSOR',
            'RANI',
            'BOTTANACS',
            'GARDEN',
            'KRAVING',
            'FISH',
            'PROPHESY',
            'NANCY',
            'PET TOUCH',
            'CHAIR',
            'IAN',
            'SCOTCH',
            'GREEN WOELD',
            'TIME',
            'NUMBER 1',
            'JEWELERRY',
            'FRUCTIES',
            'CHEERS',
            'POWER FULL',
            '3.S',
            'CASTLE BEJAR',
            'DISTALGESIC',
            'REFRESHING',
            'BLACK',
            'NERO',
            'GALSS',
            'MISSVERA',
            'THE EARTHS',
            'MCC',
            'JENAM',
            'KELLOGES',
            'CC Advance Gluco Meter',
            'MR.FALOODA',
            'CO FRESH',
            'BENSON',
            'DIGITAL',
            'RITE',
            '7',
            'BRAGG',
            'SHEILD',
            'LANA',
            'EAZU',
            'EVERVESS',
            'CHEFS',
            'HOT&GOLD',
            'MUM',
            'INOVATIVE',
            'MTV',
            'VURV',
            'DENIZGULU',
            'MEN',
            'RAYEF',
            'MAGIC EILOVY',
            'SUMMIT',
            'BED',
            'COW & GATE',
            'AVENTUS',
            'LASTING',
            'COMPUTER',
            'SWEET TOUCH',
            'SAMBA',
            'TROLLS',
            'DUREX',
            'SOLID',
            'CARESSE',
            'COSWIN',
            'LDNIO',
            'CHIP',
            'SOUVENIR',
            'DIU TANSIN',
            'BREEO',
            'WTB',
            'WATERS',
            'D-MAN',
            'SNAIL',
            'SHH',
            'ADRINA',
            'MIAOON',
            'CHIPSUP',
            'MEADOWLEA',
            'FEBREEZ',
            'COLORIST',
            'SENSODYNE',
            'AJMAL',
            'DEL MONTE',
            'MAHMOOD',
            'SUNLIGHT',
            'NOXZEMA',
            'INSTYLER',
            'SPACE',
            'HALLS',
            'PARIS',
            'TESCOMA',
            'BLOSSOM ESSENCE',
            'DAQAN',
            'CH',
            'MUMTAZ',
            'SHEER',
            'WELLS',
            'TIN',
            'CRISPICO',
            'EL SABOR',
            'SAVANNAH',
            'PAONE',
            'AJINOMOTO',
            'CATHERINES',
            'ROSSMOOR',
            'WAWEL',
            'MANHATTEN',
            'VIOLET',
            'FAIR&LOVELY',
            'RADIANCE',
            'ETERNITY',
            'YSL',
            'LANCOME',
            'KITCHEN KING',
            'ANHAAR',
            'HUGGIES',
            'NEXT',
            'FRUIT PLUS',
            'FAIREVER',
            'EMPER',
            'KISAN',
            'JASMINE',
            'JACOBS',
            'CALYPSO',
            'HELIOS',
            'AZZURRA',
            'REE',
            'MEOW MIX',
            'APTAMIL',
            'C&C',
            'SANDISK',
            'SCHWARZKOPF',
            'DURALEX',
            'DELIPOP',
            'KERNAL POP',
            'LA SUPREME',
            'ZARTAB',
            'SEVEN HERBAL',
            'MA-NO',
            'DELUX',
            'FRESH GARDEN',
            'RSEXTRA',
            'OGX',
            'JANSSEN',
            'BOSE',
            'DIKAOU',
            'RENOIRSE',
            'MASAFI',
            'SATEEN',
            'ANOVIA',
            'FANCY FEAST',
            'DAIRY LIFE',
            'FAST ACTION',
            'DAVIDAFF',
            'FRUIT OF THE EARTH',
            'BIZIM MTFAK',
            'TAMPAX',
            'GRANS',
            'DANY',
            'OILATUM',
            'PERSIL',
            'CHARILIE',
            'ALMO',
            'CREME 21',
            '4KAKA',
            'MAXIMATE',
            'LAKEME',
            'X+C',
            'MALTESERS',
            'LOOSE',
            'MILKANA',
            'SERVING',
            'SET&TOUCH',
            'BAKERS CHOICE',
            'TEN TEN',
            'MANDOLINE',
            'ARCUISINE',
            'HERMAN',
            'NATURES HOME',
            'NATKAO',
            'BANAI',
            'BANGLA',
            'SINCERE',
            'LUGLIO',
            'SANIDERM',
            'AMERICAN HARVEST',
            'TRIPLE',
            'ESPANIA',
            'PAPER',
            'NAWABgANIC',
            'FEROZSONS',
            'NYMPH',
            'LICE',
            'BAMBOO',
            'DESKTOP',
            'SHIJAY',
            'SHIRES BAKERY',
            'GOREY',
            'EHOPARD',
            'THREE',
            'PRESTO',
            'MEELA',
            'PEDIA',
            'BD',
            'TOSHIBA',
            'REMLA',
            'NATURE\'S OWN',
            'SOUP NUT',
            'SHIRLEY MAY',
            'ROYALTY',
            'AL REHAB',
            'CLOSEUP',
            'STRICTLY',
            'BALDESSARINI',
            'BOSS',
            'AMBROSIA',
            'FLOOR',
            'COMELLE',
            'KNOOR',
            'HARVIN',
            'JIMMAM',
            'REDDOLFIW',
            'TOYONASIC',
            'GOOD DAY',
            'UJALA',
            'DASTAK',
            'BIOAOUA',
            'RUMBA',
            'THRVE',
            'BABISIL',
            'KITTY KAT',
            'AL AQSA',
            'AL-RAZA',
            'KOLLY',
            'BLACK & DECKER',
            'BLEU',
            'GO ROYALE',
            'CAMEL',
            'RIGEl',
            'TIFFNY',
            'DORCO',
            'BABA',
            'HOOPIX',
            'TRI',
            'GLO',
            'MOULINEX',
            'INTEX',
            'THE SALT COMPANY',
            'SHAKAR',
            'XINBAO',
            'LOCK & LOCK',
            'FRUTI-O',
            'ALGO',
            'BIRBO',
            'MR.WHITE',
            'ZACT',
            'GUL GOLD',
            'AIYB',
            'HELLMANNS',
            'TUARNA',
            'LOACKER',
            'ME',
            'MISLINE',
            'WALKERS',
            'AIRPURE',
            'ARIZONA FIELDS',
            'MAZOON',
            'CATCHCAT',
            'GLOW & LOVELY',
            'ARGAN OIL',
            'DERMASENSE',
            'SUNSILK',
            'DAZZ MATTAZZ',
            'ARTIFICIAL',
            'CONTOURING',
            'DIANA',
            'MONCARA',
            'FERRERO',
            'BOUNTY',
            'KIT KAT',
            'FLAMINGO',
            'OLIO',
            'PLANTA',
            'MYSTIQUE',
            'RAFHAN',
            'RESTORIA',
            'DERMACOL',
            'TIGER',
            'FOOD NET',
            'A-ONE',
            'TIANNUO',
            'OH MY',
            'DELICES',
            'TWIX',
            'SNICKERS',
            'NOBLE',
            'TRASIT',
            'US POLO',
            'ALL SEASONS',
            'DELICE',
            'CO-NATURAL',
            'CAPTURE',
            'PUREDERM',
            'EXAGGERATE',
            'DISPEL',
            'BNB',
            'COLOUE ME',
            'LICHCN',
            'FRESCO',
            'XAVIER LAURENT',
            'ORO',
            'FLORET',
            'CHIVITO',
            'GEEMY',
            'AIZHIANO',
            'KILITE',
            'MOVENPICK',
            'HABIB',
            'TOBLERONE',
            'RAFFAELLO',
            'DREAMIES',
            'INSPIRE',
            'MOOV',
            'AFNAN',
            'GENTELLE',
            'FRUTI',
            'MURREE BREWERY',
            'A&N',
            'FORMULA',
            'BLACK MAGIC',
            'ALMA',
            'ROYAL LATHER',
            'BISCOTTO',
            'MYCELL',
            'HUAWEI',
            'SOLUGHOL',
            'MR.PAPE',
            'HER',
            'CHALO',
            'H&S',
            'ACCENT',
            'ALBA',
            'LAZIZA',
            'SAFE & CLEAN',
            'MEPRO',
            'SALVO',
            'CAP',
            'WISH FUL',
            'FIT',
            'TAPE',
            'TOUCH & GO',
            'Mr. MASHROOM',
            'QUEENS',
            'MOCHOS',
            'UNIQUE',
            'GRACE',
            'NITRO',
            'ZARAFA',
            'PRIVATE',
            'MAHARANI',
            'FACIA',
            'AIR PRO',
            'DOLE',
            'CREATION',
            'DEXE',
            'EXPLORE',
            'GATORADE',
            'MAX SCRUB',
            'MR.',
            'LORENAY',
            'JOHNAONS',
            'NARS',
            'GOFRES',
            'RONCATO',
            'MISBAH',
            'CHO CHO',
            'GO4 GLOW',
            'KIRI',
            'RUUD',
            'NERSISSUS',
            'CHELSEA',
            'POPPINS',
            'DENTYNE',
            'ITALA',
            'MR.PICKLE',
            'MAXBAR',
            'BATOOK',
            'DISAAR',
            'SLIPERS',
            'GRAB',
            'hobbyy',
            'NUTRI BAKER',
            'INDO LINE',
            'ALPEN',
            'SIDER',
            'DUO',
            'JIF',
            'CONCORD',
            'GUMOUT',
            'VIZYON',
            'DUMANI',
            'BUTCHERS',
            'ECONA',
            'KUKU',
            'KNOCK OUT',
            'CERISE',
            'SCILIFE',
            'NUTRILOV',
            'AMERICAN CARE',
            'JOY',
            'DTALIANO',
            'MATTE',
            'LURPAK',
            'TORTO',
            'JINNY BALL',
            'M&M',
            'PYRAMID',
            'FERRY ROSE',
            'SPARK',
            'CELEBRATIONS',
            'KIT',
            'NUTRILIGHT',
            '7 STICK',
            'KUKE',
            'VICEROY',
            'KORNEEZ',
            'TOFI LUK',
            'MILANO',
            'SHIRIN ASAL',
            'AL QUDS',
            'BELLE',
            'SHAFAQ',
            'FRUTON',
            'PERRIER',
            'ELITE',
            'IFG',
            'CAVHERE',
            'LOURENA',
            'AUSSIE',
            'ORBIT',
            'CHEETOS',
            'Adicovil injection  2 ml',
            'STP',
            'HERMESETAS',
            'LACES',
            'Roviros 10 mg Tab',
            'Estic 20 mg Cap',
            'Estic 40 mg Cap',
            'CHROME',
            'CHUPA',
            'Sualin Tab',
            'TARANG',
            'Distal Water  5ML',
            'Cotton rool 25 gm',
            'TRIM-II',
            'Petrolium Jelly 10 gm',
            'SINGHAR',
            'TIC',
            'BABYB',
            'Balingo injection 10 ml',
            'ZUBAIR',
            'Roviros 5 mg Tab',
            'Hyzith 250 mg Cap',
            'Inflamatix SR cap',
            'SODA',
            'PREAL',
            'SOLO',
            'MUST',
            'SAEFGUARD',
            'RING',
            'WAVY',
            'ENO',
            'Affif 250mg Tab',
            'LUDE',
            'NIPPLE',
            'DENTIST',
            'Castor Oil Pure (Ovel) 25 ml',
            'Cotton rool 50 gm',
            'SOFTMINT',
            'YOKO',
            'MO GIRL',
            'AMBASSADOR',
            'TOOTH',
            'SUHAGAN',
            'AROOSA',
            'SOUNF',
            'SNACKS',
            'FICO',
            'SKIN',
            'LOTTEGUM',
            'KARACHI',
            'SAFON',
            'Brace Mix (Local)',
            'MILCO',
            'NAZ',
            'INSTUM',
            'Vomi Tab',
            'PAW',
            'CHIPS',
            'SHELL',
            'ALLURA',
            'TOMMY',
            'LINKUS',
            'Cithrox 250 mg Tab',
            'Angesic Tab',
            'VITAMIN',
            'Voveron',
            'Spon-K Tab',
            'Muscadol Fort Tab',
            'ANGEL',
            'calcitron Cap',
            'TOE',
            'Roviros 20 mg Tab',
            'TRIM',
            'SLICE',
            'SAUNF',
            'NIMKO',
            'MOM-FOLIC Tab',
            'Riam 400 mg Tab',
            'I-Bid 100 mg Tab',
            'Panaxcy 20 mg',
            'Kamic  Tab',
            'MIRINDA',
            'CHIC',
            'LEMON',
            'BAY',
            'SAGU',
            'QASURI',
            'VITAMIN-C',
            'METFORMINA TAB 1 GM',
            'STING',
            'LOUD',
            'CENTER',
            'FAY',
            'HENNA',
            'MOKATE',
            'STUD',
            'Surgee Crepe 3 inch',
            'TEC-II',
            'KELLY',
            'JOSH',
            'KNIGHT',
            'ELLIPS',
            'CHAMPION',
            'WAX',
            'TUSER',
            'Orthram 20 mg Tab',
            'Axalor 10 mg Tab',
            'Dilzem 60 mg Tab',
            'Dilzem 30 mg Tab',
            'Davicobal Tab',
            'ESCORT',
            'GUR',
            'Regulair 5 mg Tab',
            'I-Cobal Tab',
            'Vizin 2 mg Tab',
            'Soneta 2 mg Tab',
            'Pulse 25 mg Tab',
            'XINJIEDA',
            'Vitatron Cap',
            'Bio-Zinc cap',
            'AUTO',
            'TH',
            'M',
            'VINKA',
            'ANNE',
            'GENERATION',
            'MENA',
            'Lonacort 1 ml Inj',
            'KALA KOLA',
            'Diuza 25 mg Tab',
            'Nemsis 100 mg Tab',
            'Puldol 50 mg Tab',
            'Feldene 10 mg Tab Dis',
            'RECKITT BENCKISER',
            'Kamic Fort Tab',
            'KELIANG',
            'BABBY',
            'METALIC',
            'ILLACHI',
            'FEATHER',
            'METRO',
            'DELVE',
            'COSEE',
            'CHARMING',
            'BAISEN',
            'STARCH',
            'TOUCH ME',
            'PHATKARI',
            'MISHRI',
            'ALSI',
            'AJWAIN',
            'AUX',
            'Puldol 100 mg Tab',
            'Feldene 20 mg Tab Dis',
            'Bone Plus TAb',
            'Dioplus 5/80 mg Tab',
            'OMUNG',
            'SAYS',
            'DIOVAN',
            'EVEREADY',
            'SUGARIE',
            'LIBIDO',
            'SHENGJIE',
            'K.NAIL',
            'FAVOURITE',
            'ISPAGHOL',
            'STREPSILS',
            'Rosuva 20 mg Tab',
            'Palmol Plus Tab',
            'Fine Blood Tab',
            'STANDPHARM',
            'TABROS PHARMA',
            'BHAI',
            'BALLOONY',
            'BAJRA',
            'SUJI',
            'CARESSA',
            'Arynon 20 mg Cap',
            'SB',
            'AGINOMOTO',
            'NUK',
            'NAUNEHAL',
            'WISTO',
            'MAIDA',
            'CHANNA',
            'BALOONS',
            'CPT',
            'Introcan 24 G',
            'KROX',
            'DIPLOMAT',
            'ESHAAN',
            'PETROLEUM',
            'TOILET',
            'Umbilica Gel 10 gm',
            'SHINEX',
            'JOLLY',
            'SPICY',
            'CRISPY',
            'PAKORIAN',
            'MISTER',
            'TOP-TIP',
            'ASPIN PHARMA',
            'ALI',
            'LAHORI',
            'Alergo 10 mg Tab',
            'NEXT PHARMACEUTICAL',
            'CHASHNIK',
            'MOSPEL',
            'Enziclor Gel 30 gm',
            'MASH',
            'LOBIA',
            'Surgical Tape 1/2 inch',
            'GHARELLO',
            'LIPSTICK',
            'ARCHE',
            'AVON',
            'ALL CLEAR',
            'Cithrox 500 mg Tab',
            'Valtec AM 5/160 mg Tab',
            'OFF',
            'Toot Siah 60 ml syp',
            'SADIQ',
            'SONF',
            'OOLALA',
            'NUTCITY',
            'HALCHAL',
            'GINGER',
            'METHRAY',
            'ARDOR',
            'GREEN',
            'TAPLAL',
            'MIAOW',
            'ABU',
            'MACHO',
            'FONG',
            'IPAKY',
            'Bendazole Tab',
            'Flexezen Tab',
            'Celd  Tab',
            'Valtec AMH 5/160/12.5 mg Tab',
            'Lutevit Advance Tab',
            'Curezol ream 10 gm',
            'TOPS',
            'CORIANDER',
            'KHATAI',
            'POPY SEED',
            'Diasar 5/80 mg Tab',
            'Dogrel 75 mg Tab',
            'HELIX PHARMA',
            'FIRE',
            'FLYING',
            'BLACK BEAUTY',
            'TANGO',
            'APRICOT',
            'LIAO',
            'HAMMER',
            'MENTA',
            'MAYFAIR',
            'ROUGH',
            'Levofloxa 500 mg Tab',
            'ROCKET',
            'JENPHARM',
            'Dioplus 10/160 mg Tab',
            'Gliptin 100 mg Tab',
            'SALED',
            'KIDCO',
            'SAFI',
            'DAILY',
            'ALOBON',
            'BE',
            'SELFIE',
            'KALWANJI',
            'SESMI',
            'Adhesive Plaster Tape 1 inch',
            'IMLEE',
            'DIZNEE',
            'TURMERIC',
            'GOND',
            'LITTLE',
            'COCONUT',
            'FLUORESCENT',
            'RED',
            'TATRI',
            'CHANDI WARQ',
            'Clinda PlusGel 10Gm',
            'BACK',
            'CATHERINE',
            'LUV',
            'CHAAT',
            'QRAISE 100 TAB',
            'Valtec AMH 10/160/25 mg Tab',
            'Lipride 100mg Tab',
            'DENTONIC',
            'NINE LESVES',
            'FAIR MENZ',
            'BRIDO',
            'Clariset 500 mg Tab',
            'Dioplus 5/160 mg Tab',
            'Valtec AMH 10/160/12.5 mg Tab',
            'Manacid Fort Syp',
            'PLUM',
            'MOON',
            'INTELLIGENCE',
            'Udic Cream 15 gm',
            'KOHINOOR',
            'SHARPER',
            'RAAY',
            'HYGEX',
            'AY',
            'Efamol Active cap',
            'Survive 40 mg Tab',
            'Viglip-m  50/500mg',
            'SNOW',
            'BIRTHDAY COLOURS',
            'KR',
            'MECHICO',
            'MAI',
            'NOVARTIS',
            'ENERGILE',
            'Levofloxa 250 mg Tab',
            'Derm Save Lotion 100 ml',
            'FESTIVAL',
            'AMLAY',
            'ANARDANA',
            'DERMOVATE',
            'Valtec AM 5/80 mg Tab',
            'Diasar 10/160 mg Tab',
            'MOCCONA',
            'Crecent maternity Pad',
            'DEBELLO',
            'MILKE',
            'YENI',
            'MOSHI',
            'VINDA',
            'Udic-B Cream15 gm',
            'CLAYPSO',
            'BOTTLE',
            'PREMA',
            'DEZINER',
            'DEMAND',
            'ZIPPER',
            'WELLOXON',
            'SMARTIES',
            'BARIAN',
            'SEKA KAI',
            'AJAX',
            'Udic-H Cream15 gm',
            'FRUITS',
            'MULATHI',
            'DENRAL',
            'Advacort  0.1% oint 10 gm',
            'Calzee Calcium +D3 Tab',
            'Mox-Q 400 mg Tab',
            'GLAXOSE-D',
            'ARTMATIC',
            'NCC',
            'BAOLILAI',
            'FRESHER',
            'WOODWARD',
            'KESH',
            'HB',
            'TUKMALANGA',
            'MASOOR',
            'STICKER',
            'BEAUTI',
            'JEWELADE',
            'FEEDER',
            'IVORY',
            'ANNAM',
            'Lubrex Lotion 40 ml',
            'SODA WHITE',
            'NORANGI',
            'HERS',
            'AQUAFINA',
            'GLAMOROUE',
            'RAISEN',
            'CUMIN',
            'PASCUAL',
            'DEEP',
            'DIWAN',
            'HUSSAIN',
            'CHICKOO',
            'GARAM MASALA',
            'JASCO',
            'CINEMON',
            'JAIFAL',
            'DOY',
            'Ezi Breath Balm 19 gm',
            'HIGH',
            'ROOMI',
            'MT',
            'CAMAY',
            'INTU',
            'PARADISE',
            'CLOVE',
            'MANAKA',
            'EVIAN',
            'BRAVO',
            'SOCKS',
            'BOND',
            'Ce-Rex Cough Syp',
            'ABUDAWOOD',
            'Suduri Sugar Free 120ml syp',
            'KARA',
            'ARONI',
            'SURPRISE',
            'CURRY',
            'WOOL',
            'MAAN',
            'Tablet Box (L) 7 days /3 Time',
            'KAJARA',
            'JY',
            'ZEST',
            'SURPISE',
            'MOONG',
            'WINDEX',
            'ROSE',
            'SHAMI',
            'CUTTER',
            'JOINER',
            'BLUSHER',
            'KAMAR',
            'NAPHTHALENE',
            'PEELER',
            'Valtec AM 10/160 mg Tab',
            'TOKRI',
            'PHILIS',
            'HELPER',
            'CLOSE',
            'FERRORI',
            'SOFIT',
            'BURGER',
            'FRUITY',
            'POLY',
            'BOOTS',
            'MARA',
            'LES',
            'GHIDINI',
            'DOI',
            'MISTINE',
            'Ezi Fiber Classic 45 gm',
            'DATES',
            'PALTTA+DOI',
            'PARATHA',
            'FPRHANS',
            'ITCH',
            'GHARELOO',
            'ROPE',
            'KADOO',
            'HISCO',
            'BISCUIT',
            'KOPIKO',
            'BADEYA KHATAI',
            'COTTON',
            'Suduri 120ml syp',
            'Safi 175 ml syp',
            'BELL',
            'TROIS-CIRCLE',
            'RIO',
            'YESNOW',
            'NOMARKS',
            'SPRAY',
            'REFUSE',
            'UGLOBE',
            'HANDFREE',
            'CROWL',
            'KELLUGGS',
            'GIFU',
            'FAMOUS',
            'CC Advance Strips',
            'JEWELLERY',
            'RUBICON',
            'CARTOON',
            'SOGO',
            'FRISKY',
            'JAZ',
            'BAYARA',
            'FINDER',
            'FEMINA',
            'NO.1',
            'RIVO',
            'Cola Gin Sachets',
            'YOWE',
            'SWISH',
            'C',
            'HEART',
            'Lubrex Lotion 75 gm',
            'FORGED',
            'MAMEE',
            'FRIDGE',
            'MEDICINE',
            'LAZZAT',
            'OMROC',
            'POWERZOOM',
            'KEYCHAIN',
            'BARBICAN',
            'KABAB',
            'DEBUTANTE',
            'MA',
            'NESLTE',
            'KUNGFU',
            'KETCHUP',
            'SPARKLE',
            'BEARDY',
            'FLY',
            'CHAABI',
            'OTG',
            'BOP',
            '69613',
            'STRAW',
            'RIVAJMATT',
            'URINAL',
            'GOFY',
            'LADY',
            'SHINE BEAUTY',
            'HOOK',
            'LENOVO',
            'FAULTLESS',
            'MUMI',
            'MAM',
            'MELODY',
            'MEZITA',
            'COOL',
            'TAFT',
            'FOSHER',
            'KARCM',
            'BACKING',
            'CARNATION',
            'NOZZLE',
            'DORY',
            'Bambo',
            'SHUNHANG',
            'PUMA',
            'SCHWEPPES',
            'SOCK',
            'BOTHER',
            'SUNNY',
            'XSTAR',
            'AURA',
            'PEGEON',
            'MOTOMO',
            'HOJAR',
            'MAKHANY',
            'SIMPLEX',
            'GREN',
            'Cell D Plus cap 1,s',
            'GARNIRA',
            'BIRYANI',
            'SPATULA',
            'SELECT',
            'RUGMASTER',
            'NEXERA',
            'PIXY',
            'CANADA',
            'LOTA',
            'DERMOVIA',
            'DARLIE',
            'NAMAK',
            'AIZHILANO',
            'FEAH',
            'QUEST',
            'HIT',
            'BALLOON',
            'LUI',
            'LISTRERINE',
            'MARBAL',
            'STAND',
            'BON',
            'IMPULSE',
            'NOODLE',
            'TABASCO',
            'PEARL',
            'REMAX',
            'SI',
            'PIN',
            'PHOENIX',
            'CUTICURA',
            'VOLUME',
            'REMOTE',
            'LIVON',
            'MAAZ',
            'SANCHA',
            'WET',
            'NOOR',
            'MEFICAM',
            'POT',
            'SAMSARA',
            'LG',
            'CHAMCHA',
            'GRATER',
            'QUORUM',
            'DESIRE',
            'REATION',
            'GIRL',
            'SILLIS',
            'DUMPLING',
            'AL ARIJ',
            'DAIMEND',
            'FEEL',
            'KHAMKHEER',
            'CHAKLA',
            'GURDALL',
            'NIHAR',
            'MOREN',
            'MARINDA',
            'MEDICAME',
            'KLIP',
            'NOSTA',
            'No More Leucorrhoea',
            'HAIER',
            'AL KAREEM',
            'VENUS',
            'GIPSY',
            'FINISH',
            'KINDER',
            'DUE',
            'WEETOS',
            'FIESTA',
            'STSR',
            'LADDER',
            'KRACK',
            'CAREFREE',
            'BATMAN',
            'REDOX',
            'STEVIA',
            'SQUARE',
            'EUROCAKE',
            'MISWAK',
            'KULFI',
            'KLUMPY',
            'HELLMANN,S',
            'BRAGA',
            'NETWORK',
            'ADVANCE',
            'SOL',
            'CLIP',
            'THE BODY SHOP',
            'DK ONE',
            'VASELINR',
            'ACTION-C',
            'PURE WHITE',
            'EYESHA',
            'MR POINT',
            'MAJIX',
            'ORGANIC',
            'TOOTHPICK',
            'VENEZIA',
            'SANDAL',
            'MOIZ FOODS',
            'CUTEPLUS',
            'SKIPPY',
            'CHICCO',
            'MR.OLIVES',
            'WASAL',
            'PARLEY',
            'DIGESTIVES',
            'Adhesive Plaster Tape 3 inch',
            'FELL',
            'ENFAMAMA',
            'FLEX',
            'DRAIN',
            'MANO SALWA',
            'VELVET',
            'KITEKAT',
            'EMERON',
            'GUN',
            'LOVE JOJO',
            'Titz',
            'CAPPY',
            'DRE.ORTHO',
            'CONFIDENCE',
            'NATURELLA',
            'THOMAS',
            'MOLPED',
            'EMELIE',
            'MOSS & ADAMS',
            'HIFGUR',
            'FAIR EVER',
            'LUSTRE',
            'B',
            'BAOLISHI',
            'RIVAL',
            'BYTE',
            'BRASOO',
            'AMBRAY',
            'FOLI',
            'CRYSTAL',
            'LIPSTIC',
            'JOVAN',
            'GOTCHA',
            'HAWAII',
            'CHOCOLATE',
            'NAIL',
            'MAGGIE',
            'GANDOUR',
            'OMUDA',
            'RI',
            'M&MS',
            'O.FOOD',
            'DORAEMON',
            'EURO BAKE',
            'SUPER CRISP',
            'INTENSIEYE',
            'SUNNY MUKHWAS',
            'DOSTEA',
            'HAJMOLA',
            'KENT',
            'REMILNGTON',
            'RAYAN',
            'BREAD&BWYOND',
            'NOODI',
            'ROSEPETAL',
            'MUTUAL LOVE',
            'NOCILLA',
            'RUSH',
            'RENATA',
            'SAVOLI',
            'ALPELIEBE',
            'DENGLENG',
            'CYCLAX',
            'MAJESTIC',
            'MR.CANDY',
            'INSTRUCTION',
            'ASDA',
            'GILTZ',
            'HOLSTEN',
            'CHAPET',
            'SUNDROP',
            'MILKY',
            'MANPASAND',
            'CARBURY',
            'Lutevit Advance syp',
            'PALMA',
            'LANTHERIC',
            'THIS',
            'MAROOF',
            'CAMELLIA',
            'WEIGHT',
            'STIFF ON',
            'SOFT N SHINE',
            'MONESCO',
            'FRUITI-O',
            'FARLEYS',
            'NARCISSUS',
            'FIELDS',
            'TOUCH',
            'NUMBER',
            'WADI',
            'SWISS',
            'AURORA',
            'MAQBOOL',
            'WOOLEN',
            'Bendazole Syp',
            'RUBY GO LOCAL',
            'SABALIN',
            'Valtec AMH 5/160/25 mg Tab',
            'HOTWHEEL',
            'GERNIER',
            'BARLIE',
            'OPOOLA',
            'MAXMAN',
            'RELATION',
            'TERRE',
            'SAKURA',
            'COLOSSEUM',
            'VATICKA',
            'HOLY COW',
            'FOUR',
            'KANGAROO',
            'O',
            'NORTHESE',
            'JAM',
            'MANES',
            'SOFTMINTS',
            'ACRYL',
            'AIUB',
            'COOKIES',
            'ENTHRICE',
            'SEEKH',
            'FOLLOW',
            'NIIVEA',
            'ROBOROBO',
            'PICNIC',
            'LOCK&LOCKFOOD',
            'INSURECTION',
            'HEATER',
            'TRAP',
            'PANTRY',
            'BAKERS',
            'LOUIS CARDIN',
            'MANIPOL',
            'CHOCO',
            'VIANO',
            'DELAVIUDA',
            'NAKED3',
            'R/C',
        ];
        $uuid = 88311222282037;
        $i = 1;
        foreach ($data as $row){
            $row = trim($row);
            $name = strtolower(strtoupper($row));
            if(!\App\Models\TblPurcBrand::where(\Illuminate\Support\Facades\DB::raw("lower('brand_name')"),$name)->exists()){
                \App\Models\TblPurcBrand::create([
                    'brand_id' => $uuid,
                    'brand_name' => $row,
                    'brand_entry_status' => 1,
                    'brand_user_id' => 81,
                    'business_id' => 1,
                    'company_id' => 1,
                    'branch_id' => 1,
                ]);
                $uuid = $uuid + $i;
                $i = $i + 1;
            }
        }
    }
}
