<?php

use Illuminate\Database\Seeder;

class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ["AFZAL AGANCIES (HAPPY COW)","LOCAL VENDORS-B","0","0",],
            ["I&K IMPEX (NEXTON)","LOCAL VENDORS-B","30","0",],
            ["RAFI TRADERS (BIC BODY)","LOCAL VENDOR-C","0","0",],
            ["LAHORE PERFUME (SHAH ALAM)","SHAH ALAM VENDOR -C","0","0",],
            ["A & M MARKETING (SUPER CRISP)","LOCAL VENDORS-B","0","0",],
            ["ZINSAS INTER NATIONAL (PUR) PREV 3A MARKETING","LOCAL VENDORS-B","0","0",],
            ["MALKANI TRADERS (CHIP UP)","LOCAL VENDORS-B","0","0",],
            ["A & N SERVICES (AL-MARAI)","LOCAL VENDORS-B","0","0",],
            ["A & N SERVICES (QUAKERS)","LOCAL VENDORS-B","0","0",],
            [" A M SAEED (SHAH ALAM)","SHAH ALAM VENDOR -C","0","0",],
            ["A.R BOUTIQUE","LOCAL VENDOR-C","","",],
            ["SAJID TRADING PREV A/C ARIF","SHAH ALAM VENDOR-B","0","0",],
            ["AAMER BROTHERS (URDU BAZAR)","SHAH ALAM VENDOR -C","0","0",],
            ["ABDUL GHANI MEDICINE COMPANY","LOCAL VENDORS-B","0","0",],
            ["ABDUL HAMEED ENTERPRISES","LOCAL VENDOR-C","0","0",],
            ["MAMTA ENTERPRISES (CROCKERY)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["ABDULLAH HAROON","LOCAL VENDOR-C","","",],
            ["U & S INDUSTRIES (IPSA) PREV ABDULLAH TRADERS LAHORE PERFECT ","LOCAL VENDORS-B","0","0",],
            ["ADAMS (UNDER GARMENTS)","LOCAL VENDOR-C","0","0",],
            ["ADIL PLASTIC INDUSTRIES","SHAH ALAM VENDOR -C","0","0",],
            ["ADNAN PAKAGES DISPOABLE ITEMS","LOCAL VENDOR-C","","",],
            ["AFZAAL AGENCIES (LOCK & LOCK)","LOCAL VENDOR-C","","",],
            ["AFZAAL AGENCIES (NIDO)","LOCAL VENDORS-B","0","0",],
            ["AFZAAL AGENCIES (TESCO)","LOCAL VENDORS-B","0","0",],
            ["AFZAL ENTERPRISES ( HABIB OIL)","LOCAL VENDORS-B","0","0",],
            ["AFZAL PEN CENTRE (SHAHALAM)","SHAH ALAM VENDOR -C","","",],
            ["AFZAL TRADERS CANDYLAND","LOCAL VENDORS-B","0","0",],
            ["AH COLLECTION (GARMENTS)","LOCAL VENDOR-C","","",],
            ["AHAD TRADING COMPANY (SHAH ALAM)","SHAH ALAM VENDOR -C","","",],
            ["AZ MARKETING (TIFFANY)","LOCAL VENDOR-C","0","0",],
            ["AHG LAHORE (NIVEA)","LOCAL VENDOR-C","0","0",],
            ["MULTI INTERNATIONAL BRANDS (SUPER CRISP)","LOCAL VENDORS-B","0","0",],
            ["AHMAD IMPEX","SHAH ALAM VENDOR -C","0","0",],
            ["AHMAD SAEED AND COMPANY (KLUMPY)","LOCAL VENDOR-C","0","0",],
            ["SELECTION PLUS (AHMED ILLHI)CROCKERY","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["Ahmed traders (Shoping Bags)","LOCAL VENDOR-C","0","0",],
            ["AHSAN ELAHI CORPORATION (CROCKERY)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["AHT TRADERS (MOBILE ACCESSORIES)","SHAH ALAM VENDOR -C","0","0",],
            ["AIK BROTHERS (NURPUR)","LOCAL VENDORS-B","0","0",],
            ["AK MARKETING (BLACK ROSE)","LOCAL VENDOR-C","0","0",],
            ["AKS DISTRIBUTION HOUSE (CALIFORNIA)","LOCAL VENDOR-C","","",],
            ["AZ MARKETING (MOTHERCARE)","LOCAL VENDORS-B","0","0",],
            ["AL AMIN TRADERS (MARHABA)","LOCAL VENDORS-B","0","0",],
            ["AL FATAH TOYS (SHAHALAM)","SHAH ALAM VENDOR -C","0","0",],
            ["AL FAZAL TRADERS (PAKOLA DRINK)","LOCAL VENDORS-B","0","0",],
            ["AL HARAM TRADER(KING TEA)","LOCAL VENDOR-C","","",],
            ["AL MADNI EGG","LOCAL VENDORS-B","0","0",],
            ["AL NOOR GARMENTS","SHAH ALAM VENDOR -C","","",],
            ["AL NOOR TRADER (BIO AMLA)","LOCAL VENDOR-C","","",],
            ["Z.H ENTERPRISES  (STILLMAN) PREV AL QAMAR DISTRIBUTOR","LOCAL VENDOR-C","0","0",],
            ["AL QAMAR DISTRIBUTOR-LAHORE PHARMA","LOCAL VENDOR-C","0","0",],
            ["AL RAZZAAQ TRADING (FLORA TISSUES)","LOCAL VENDOR-C","","",],
            ["ALFEE TRADERS (COCMIC)","LOCAL VENDOR-C","","",],
            ["ALI & CO (KENYA TEA)","LOCAL VENDOR-C","","",],
            ["ALI BROTHERS (SKIN WHITE)","LOCAL VENDOR-C","0","0",],
            ["ALI GARMNETS","SHAH ALAM VENDOR -C","","",],
            ["ALI GOHAR & CO","LOCAL VENDORS-B","0","0",],
            ["ALI GOHAR & CO (MAYBELLINE)","LOCAL VENDORS-B","0","0",],
            ["ALI GOHAR & CO PHARMA","LOCAL VENDOR-C","0","0",],
            ["ALI MOBIL CALLING CARD","LOCAL VENDOR-C","","",],
            ["AWAIS TRADERS (FOGG) PREV ABBAS TRADERS","LOCAL VENDOR-C","0","0",],
            ["ALLIED FOODS (TASTE LAND BISCUITS)","LOCAL VENDOR-C","","",],
            ["ALLIED MARKETING (CIGRATES)","LOCAL VENDOR-C","0","0",],
            ["ALLIED MARKETING PVT LTD (HAYAT)","LOCAL VENDORS-B","0","0",],
            ["AL-NASSER PAKISTAN (PLASTIC CROCKERY)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["ALPHA MARKETING (BLESSO)","LOCAL VENDOR-C","0","0",],
            ["ALHAMZA ENTERPRISES (KEUNE) PREV TOOR-R-SENA ","LOCAL VENDORS-B","0","0",],
            ["AZ MARKETING (SUNBEAN)","LOCAL VENDOR-C","0","0",],
            ["AMAS DISTRIBUTION NETWORK","LOCAL VENDOR-C","0","0",],
            ["AMB MOBILE ACCESSORIES","SHAH ALAM VENDOR -C","0","0",],
            ["AMMAZ ENTERPRISES (PHARMA)","LOCAL VENDOR-C","0","0",],
            ["ANUM COMMUNICATION","LOCAL VENDOR-C","","",],
            ["ARG BABU BHAI GARMENTS","LOCAL VENDOR-C","0","0",],
            ["FOODEX TRADERS PREV ARIF BROTHERS","SHAH ALAM VENDOR-B","0","0",],
            ["ARIQ INTERNATIONAL (CROCKERY)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["AROOJ TOWEL INDUSTRIES","LOCAL VENDOR-C","0","0",],
            ["ASAD TRADING CO","LOCAL VENDOR-C","","",],
            ["ASHFAQ TRADERS(SHAH ALAM)","SHAH ALAM VENDOR -C","0","0",],
            ["ASHRAF & COMPANY","LOCAL VENDOR-C","","",],
            ["ASHRAFIA DISTRIBUTORS","LOCAL VENDOR-C","","",],
            ["ASIA ELECTRIC STORE","LOCAL VENDOR-C","","",],
            ["ASIA TRADING CO. (CROCKERY)","LOCAL VENDOR-C","","",],
            ["ASIF BROTHERS(SHAH ALAM)","SHAH ALAM VENDOR -C","","",],
            ["AST TOYS","LOCAL VENDOR-C","","",],
            ["ASTACO BELL","LOCAL VENDOR-C","","",],
            ["ATA BAKERY SOLUTIONS","LOCAL VENDORS-B","0","0",],
            ["ATC PULSES","LOCAL VENDOR-C","","",],
            ["ATCO (FOOD)","LOCAL VENDORS-B","0","0",],
            ["ATCO (P&G)","LOCAL VENDORS-B","0","0",],
            ["ATIF WAHEED & CO (FAUJI PASTA)","LOCAL VENDORS-B","0","0",],
            ["ATTA & SABRI SONS (SOHAN HALWA)","LOCAL VENDOR-C","","",],
            ["AT-TAHUR (PVT) PREMA MILK","LOCAL VENDORS-B","0","0",],
            ["AWAIS BROTHERS(EVA OIL)","LOCAL VENDOR-C","0","0",],
            ["THE TRADING TRACK (FAIR MARKETING) PREV AWAIS TRADERS","LOCAL VENDORS-B","0","0",],
            ["WAQAS TRADERS (INDIAN COSMETIC) PREV AWAIS TRADERS ","SHAH ALAM VENDOR-B","0","0",],
            ["AYAN TRADERS (SHAN FOODS)","LOCAL VENDORS-B","0","0",],
            ["AYESHA TRADERS (CARESSE)","LOCAL VENDOR-C","","",],
            ["AYESHA TRADERS (DIAMOND FOIL)","LOCAL VENDOR-C","0","0",],
            ["AYESHA TRADERS (NIVEA)","LOCAL VENDOR-C","0","0",],
            ["AZEEM TRADERS","LOCAL VENDOR-C","","",],
            ["AZHAR CHUNRI ARTS (GARMENTS)","LOCAL VENDOR-C","0","0",],
            ["BILAL BROTHERS NATURELLE GHEE","LOCAL VENDORS-B","0","0",],
            ["AL-HARAM TRADERS(CANDYLAND)","LOCAL VENDOR-C","0","0",],
            ["AZMAT TRADERS (EZIGRIP)","LOCAL VENDOR-C","","",],
            ["AZMAT TRADERS NOVELLA","LOCAL VENDOR-C","","",],
            ["B W TRADER(ADMIRAL)","LOCAL VENDOR-C","0","0",],
            ["BABAR MEDICINE COMPANY","LOCAL VENDOR-C","0","0",],
            ["Babar Medicine Company (Group A)","LOCAL VENDOR-C","0","0",],
            ["Babar Medicine Company (Group B)","LOCAL VENDOR-C","0","0",],
            ["Babar Medicine Company (Group C)","LOCAL VENDOR-C","0","0",],
            ["Babar Medicine Company (Group D)","LOCAL VENDOR-C","0","0",],
            ["BABY LAND COM ( SHAHALAM )","SHAH ALAM VENDOR -C","0","0",],
            ["BABYZ WORLD (SHAH ALAM)","SHAH ALAM VENDOR-B","0","0",],
            ["BAHOO TRADERS (ADMIRAL+VICEROY)","LOCAL VENDOR-C","","",],
            ["BAJWA TRADERS (LAHORI)","LOCAL VENDOR-C","0","0",],
            ["CRYSTAL PLUS PREV BASHIR TRADERS (FURNITURE)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["NAQVI TRADERS (INOVATIVE)","LOCAL VENDORS-B","0","0",],
            ["BHATTI TRADERS (OLPERS)","LOCAL VENDORS-B","0","0",],
            ["DIN ENTERPRISES (KASHMIR OIL) PREV BHATTI TRADERS","LOCAL VENDORS-B","0","0",],
            ["BHOOJAS PRESTIGE (KARACHI)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["BIG BIRD FOODS(PVT) LTD","LOCAL VENDORS-B","0","0",],
            ["BILAL BROTHER (AFNAN OIL)","LOCAL VENDOR-C","0","0",],
            ["BILAL BROTHERS (GAI GHEE)","LOCAL VENDOR-C","0","0",],
            ["BILAL BROTHERS (GAI SOAP)","LOCAL VENDOR-C","","",],
            ["TRADELINKS (MEDICAM) PREV BILAL BROTHERS","LOCAL VENDOR-C","0","0",],
            ["BILAL BROTHERS (MEZAN OIL)","LOCAL VENDORS-B","0","0",],
            ["BILAL BROTHERS (SOYA SYPREME)","LOCAL VENDOR-C","0","0",],
            ["BILAL BROTHERS(GOLDEN SUN OIL)","LOCAL VENDORS-B","0","0",],
            ["BILLA DECORATION CENTER","SHAH ALAM VENDOR -C","0","0",],
            ["Billo Paper Mart (Urdu Bazar)","SHAH ALAM VENDOR -C","0","0",],
            ["AL-NOOR TRADING PREV BIN BAKAR TOILETRIES","SHAH ALAM VENDOR-B","0","0",],
            ["BISMILLAH FAIR MARKETING (PUNJAB ATTA)","LOCAL VENDOR-C","","",],
            ["AL-HAMRA INTERNATIONAL (SHAHALAM) PREV BISMILLAH STORE","SHAH ALAM VENDOR -C","0","0",],
            ["BISMILLAH TRADERS (FRESHER JUICE)","LOCAL VENDOR-C","","",],
            ["BISMILLAH TRADERS GOLDEN PEARL","LOCAL VENDOR-C","","",],
            ["BOL WALA CARD","LOCAL VENDOR-C","0","0",],
            ["BREEZ TRADERS","LOCAL VENDOR-C","","",],
            ["BURQUE CORPORATION (PVT) LTD. (SHAN)","LOCAL VENDORS-B","0","0",],
            ["Butt & Mughal Traders- Lahore","LOCAL VENDOR-C","0","0",],
            ["C & B MARKETING (WALLS)","LOCAL VENDORS-B","0","0",],
            ["CAKES & BAKES","LOCAL VENDOR-C","0","0",],
            ["CARFUMES","LOCAL VENDOR-C","0","0",],
            ["CBC TRADING CO","LOCAL VENDOR-C","0","0",],
            ["CHANAR SUGAR MILLS LTD","LOCAL VENDORS-B","0","0",],
            ["CHANNEL LINK (OLPER)","LOCAL VENDORS-B","0","0",],
            ["BIN YOUSAF FOODS PREV CHAUDHRY FOODS PRODUCT","LOCAL VENDORS-B","0","0",],
            ["CHIEF FOOD PRODUCTS","LOCAL VENDOR-C","","",],
            ["CHINA PAK INT'L (MOBILE ACCES)","LOCAL VENDOR-C","0","0",],
            ["CHINA TRADERS","SHAH ALAM VENDOR -C","","",],
            ["CHOUDHARY FOOD PRODUCTS ( DRY FRUITS) ","LOCAL VENDORS-B","0","0",],
            ["CHOUDHRY & SONS","SHAH ALAM VENDOR -C","","",],
            ["CITRO PAK (FRUTIEN JUICE)","LOCAL VENDORS-B","0","0",],
            ["CITY HERBAL CARE LABORATORIES","LOCAL VENDOR-C","0","0",],
            ["HASHIM BROTHERS (CANOLIVE)","LOCAL VENDORS-B","0","0",],
            ["COCA COLA BEVREAGES","LOCAL VENDOR-C","0","0",],
            ["COCA COLA SHAFI SONS","LOCAL VENDOR-C","0","0",],
            ["CODABAR RASHEED PACKAGES","LOCAL VENDOR-C","0","0",],
            ["CONNECT MARKETING SERVICES (KOLSON)","LOCAL VENDORS-B","","",],
            ["CONSOLIDATED MARKETING (MATCH BOX)","LOCAL VENDOR-C","","",],
            ["CREATIVE ASSOCIATES (DYNAMIC)","LOCAL VENDOR-C","0","0",],
            ["CREATIVE TRADE SOLUTIONS (MOSPEL)","LOCAL VENDOR-C","0","0",],
            ["DANISH DISTRIBUTION HOUSE","LOCAL VENDORS-B","0","0",],
            ["NEW PRIME MARKETING ( GOLDEN GIRL) PREV DASTAGIR MARKETING ( GOLDEN GIRL)","LOCAL VENDOR-C","0","0",],
            ["DAWOOD INTERNATIONAL PHARMA DISTRIBUTOR","LOCAL VENDOR-C","0","0",],
            ["DAWOOD TRADERS (SHAHALAM)","SHAH ALAM VENDOR-B","0","0",],
            ["DECENT ENTERPRISES PHARMA","LOCAL VENDORS-B","0","0",],
            ["DECENT PURSES HOUSE ( SHAHALAM)","SHAH ALAM VENDOR -C","","",],
            ["DEFENCE RICE","LOCAL VENDOR-C","0","0",],
            ["DELUXE SHOES","SHAH ALAM VENDOR -C","0","0",],
            ["Denim Tag (Garments)","LOCAL VENDOR-C","0","0",],
            ["DIVINE GARMENTS","LOCAL VENDOR-C","","",],
            ["DYNAMIC BELTS","LOCAL VENDOR-C","","",],
            ["EASTERN PRODUCTS(VITAL TEA)","LOCAL VENDOR-C","0","0",],
            ["ECO GLOBEL FOODS (GLUTEN FREE)","LOCAL VENDORS-B","0","0",],
            ["EFF DEE WATER","LOCAL VENDORS-B","0","0",],
            ["EJAZ AHMED HAIR ASSESSORIES","SHAH ALAM VENDOR -C","0","0",],
            ["EJAZ STATIONERY","SHAH ALAM VENDOR -C","0","0",],
            ["ELITE BRANDS LIMITED (NATIONAL FOODS)","LOCAL VENDORS-B","","",],
            ["ELITE MARKETING(SUFI GHEE)","LOCAL VENDORS-B","","",],
            ["FAIRWAYS ENTERPRISES (CADBURY+TANG) PREV EMMADULLAH TRADER(","LOCAL VENDORS-B","0","0",],
            ["ERP BUSINESS EXPERT LICENCE","LOCAL VENDOR-C","0","0",],
            ["EVER BEST(CHEF)","LOCAL VENDOR-C","","",],
            ["EVER BRITE (KITCHEN KING)","LOCAL VENDOR-C","0","0",],
            ["NUR ENTERPRISES (CAPRI)","LOCAL VENDORS-B","0","0",],
            ["F.B MARKETING","LOCAL VENDOR-C","0","0",],
            ["H & A MARKETING LAHORE (BECUTE)","LOCAL VENDOR-C","0","0",],
            ["FAHAD TRADERS","LOCAL VENDOR-C","0","0",],
            ["GLOBAL MARKETING (KINGTOX)","LOCAL VENDORS-B","0","0",],
            ["FAIZAN ENTERPRISES (GUARD RICE)","LOCAL VENDORS-B","0","0",],
            ["Fareed Traders (Lohari)","LOCAL VENDOR-C","0","0",],
            ["FARHAT ALI PHARMALINKS (HILTON)","LOCAL VENDOR-C","0","0",],
            ["FARHAT ALI PHARMALINKS (SAMI)","LOCAL VENDOR-C","0","0",],
            ["FARM 360 (DESI EGGS)","LOCAL VENDOR-C","","",],
            ["FATIMA TRADERS","LOCAL VENDORS-B","0","0",],
            ["FAZAL ENTERPRISES(SHAHALAM)","SHAH ALAM VENDOR-B","0","0",],
            ["SUNNY FLOUR MILL (GRAIN) PREV FINE MARKETING","LOCAL VENDORS-B","0","0",],
            ["Fine Medicine Services","LOCAL VENDOR-C","0","0",],
            ["FK TRADERS (ELVAN)","LOCAL VENDOR-C","","",],
            ["FOOD FELLOWS (HAPPY COW)","LOCAL VENDOR-C","","",],
            ["FOOD FELLOWS (HASAN RICE)","LOCAL VENDOR-C","0","0",],
            ["FOOD FELLOWS (NANDOS)","LOCAL VENDORS-B","0","0",],
            ["FOREIGN TRADING CO.","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["HAMZA DAIRY PRODUCTS (WHIPY WHIP) FOUR STARS","LOCAL VENDORS-B","0","0",],
            ["HASHIR TRADING COMPANY DRY FRUIT","LOCAL VENDOR-C","0","0",],
            ["F-S TRADERS (FAST ACTION)","LOCAL VENDORS-B","0","0",],
            ["A.RAHIM FOOD (DAWN BREAD) PREV G B TRADERS","LOCAL VENDORS-B","0","0",],
            ["General Purchase","LOCAL VENDOR-C","","",],
            ["GHAFOORI STORE NEW","LOCAL VENDOR-C","","",],
            ["GHOSIA ELECTRONICS SHAHALAM","LOCAL VENDOR-C","0","0",],
            ["GLOBAL MARKETING (DAY FRESH MILK )","LOCAL VENDOR-C","","",],
            ["GLOBAL PHARMACEUTICALS (PVT) Ltd.","LOCAL VENDOR-C","0","0",],
            ["GO NATURAL (SKIN PRODUCTS)","LOCAL VENDOR-C","","",],
            ["GOLDEN CHIEF","LOCAL VENDOR-C","0","0",],
            ["GRANS.PK","LOCAL VENDOR-C","","",],
            ["GREAT SHAWL AND SUITING","LOCAL VENDOR-C","0","0",],
            ["GROUP MULTIPLE (LOCK & LOCK)","LOCAL VENDOR-C","","",],
            ["H.H SAEED (MEDORA)","LOCAL VENDOR-C","0","0",],
            ["H2 FITTERS (GARMENTS)","LOCAL VENDOR-C","0","0",],
            ["HAFEEZ RAZA ELECTRON(SHSHALAM)","SHAH ALAM VENDOR -C","0","0",],
            ["HAFIZ SHAWLL HOUSE","SHAH ALAM VENDOR -C","0","0",],
            ["ASAD TRADERS (SHAH ALAM) PREV HAFIZ TRADERS ","SHAH ALAM VENDOR -C","0","0",],
            ["MUHAMMADI TRADERS (CARESSE)  PREV HAIDER MARKETING SERVICES","LOCAL VENDORS-B","0","0",],
            ["EKADA CORPORATION (DEL-MONTE) HAIDER TRADERS","LOCAL VENDORS-B","0","0",],
            ["FATIMA DISTRIBUTION (SUFI SOAP) PREV HAJI MUHAMMAD SADIQUE ","LOCAL VENDORS-B","0","0",],
            ["HAJMERI GARMENTS","SHAH ALAM VENDOR -C","0","0",],
            ["HAJVAIRY TRADERS","LOCAL VENDORS-B","0","0",],
            ["HARIS TRADERS ( SONEX)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["Hajwari Medicine Company (Lohari)","LOCAL VENDOR-C","0","0",],
            ["HAMMAD TOYS (SHAHALAM)","SHAH ALAM VENDOR -C","0","0",],
            ["HAMZA FOODS PVT (SUFI FROZEN)","LOCAL VENDORS-B","0","0",],
            ["HAMZA LEATHER WORKS","LOCAL VENDOR-C","0","0",],
            ["HAMZA LEATHER WORKS (KASUR)","LOCAL VENDOR-C","0","0",],
            ["HAMZA TRADERS (FAISLABAD)","LOCAL VENDOR-C","0","0",],
            ["PLANTERS ENTERPRISE (HAIR OIL) HAQUE PLANTERS","LOCAL VENDORS-B","0","0",],
            ["HAROON BROTHERS GLAMOROUS FACE","LOCAL VENDOR-C","0","0",],
            ["NAVEED TRADING COMPANY (SHAHALAM) PREV HAROON BROTHERS","SHAH ALAM VENDOR-B","0","0",],
            ["RBIDHA TRDERS PREV HASHIM AND COMPANY","LOCAL VENDORS-B","0","0",],
            ["HASHIM BROTHER(EVA OIL)","LOCAL VENDORS-B","0","0",],
            ["HASSAN TRADERS (SHAHALAM)","SHAH ALAM VENDOR -C","","",],
            ["HAUT BUYS PVT. LTD.","LOCAL VENDORS-B","0","0",],
            ["HEALTH 1ST PHARMA","LOCAL VENDOR-C","0","0",],
            ["HEALTH CARE NUTRION","LOCAL VENDOR-C","","",],
            ["HEALTH VALLEY (KUNRI)","LOCAL VENDOR-C","0","0",],
            ["HFF TRADERS (DAWN FROZEN)","LOCAL VENDORS-B","0","0",],
            ["HG GARMENTS","LOCAL VENDOR-C","0","0",],
            ["HIMONT LABORATORIES (PVT) LTD.","LOCAL VENDOR-C","0","0",],
            ["HOME MADE","LOCAL VENDOR-C","","",],
            ["HAMDARD LABORATORIES LTD","LOCAL VENDOR-C","0","0",],
            ["Hussain Pharmacy ( Hussain Manjan)","LOCAL VENDOR-C","0","0",],
            ["HUSSAINI DERA (URDU BAZAR)","SHAH ALAM VENDOR -C","0","0",],
            ["I & K DISTRIBUTERS","LOCAL VENDORS-B","0","0",],
            ["I K TRADERS (NURPUR)","LOCAL VENDOR-C","0","0",],
            ["IBL KELLOGGS","LOCAL VENDORS-B","0","0",],
            ["IBL OPERATION PHARMA","LOCAL VENDORS-B","0","0",],
            ["IBL(MEDJOHNSONS)","LOCAL VENDORS-B","0","0",],
            ["IBRAHIM TRADERS (DALDA)","LOCAL VENDORS-B","0","0",],
            ["IBRAHIM TRADERS (KNOCK OUT)","LOCAL VENDOR-C","0","0",],
            ["ICON ENTERPRISES BUTTERFLY","LOCAL VENDOR-C","0","0",],
            ["IDEAL ENTERPRISES (FRESHMATE )","LOCAL VENDOR-C","","",],
            ["NADEEM IMPEX (SHAHALAM) PREV IDEAL TRADERS LAGAUGE","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["IDL CORPORATION","LOCAL VENDORS-B","0","0",],
            ["IDL CORPORATION (HEMANI)","LOCAL VENDORS-B","0","0",],
            ["IDN DISTRIBUTOR (Mitchells)","LOCAL VENDORS-B","0","0",],
            ["AH ENTERPRISES (SATEEN SOFT)","LOCAL VENDOR-C","0","0",],
            ["IHSAN TRADERS QARSHI","LOCAL VENDOR-C","0","0",],
            ["Ijaz Brothers B.P","LOCAL VENDOR-C","0","0",],
            ["IJAZ TRADERS(BLACK & DECKER)","LOCAL VENDOR-C","0","0",],
            ["MA ENTERPRISES (SHAKERGANJ) PREV ASHAR ENTERPRISERS ","LOCAL VENDORS-B","0","0",],
            ["ILYAS FANCY CROCERY HOUSE","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["IRFAN TRDERS (GIFT ITEM) PREV  IMRAN TRADERS","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["IMTIAZ GARMENTS","LOCAL VENDOR-C","0","0",],
            ["INDUS MARKETING (SAF- INSTANT )","LOCAL VENDOR-C","","",],
            ["INTERNATIONAL FOUNDATION & GARMENTS","LOCAL VENDOR-C","0","0",],
            ["INTERNATIONAL MARKETING(NOVA)","LOCAL VENDOR-C","","",],
            ["IQBAL TADERS (PHARMA)","LOCAL VENDOR-C","0","0",],
            ["IQRA ENTERPRISES PHARMA","LOCAL VENDOR-C","0","0",],
            ["IRFAN ADNAN TRADERS (SHAHALAM)","SHAH ALAM VENDOR -C","","",],
            ["ISHAQ TRADERS (FROZEN)","LOCAL VENDOR-C","0","0",],
            ["ISHAQ TRDERS ( AMERICAN GARDEN )","LOCAL VENDORS-B","0","0",],
            ["ISLAM TRADER(REVLON)","LOCAL VENDOR-C","0","0",],
            ["ISLAM TRADERS","LOCAL VENDOR-C","0","0",],
            ["ISMAIL TRADERS (ENGLISH PASTE)","LOCAL VENDOR-C","","",],
            ["J.S MARKETING SERVICES (FORHANS)","LOCAL VENDORS-B","0","0",],
            ["J.S MARKETING SERVICES (SAMSOL)","LOCAL VENDOR-C","","",],
            ["JAHANGER BOOKS","LOCAL VENDORS-B","0","0",],
            ["JAMAL AKBAR (TOWELS)","LOCAL VENDOR-C","0","0",],
            ["JAMSHED CAP HOUSE","SHAH ALAM VENDOR -C","","",],
            ["JAN ENTERPRISES","SHAH ALAM VENDOR-B","0","0",],
            ["JILANI ENTERPRISES(MEZAN TEA)","LOCAL VENDOR-C","0","0",],
            ["JZAR ENTERPRISES (BRAGG)","LOCAL VENDOR-C","0","0",],
            ["K Y TRADERS(PERFUMES)","LOCAL VENDOR-C","","",],
            ["K&NS FOODS (PVT) LIMITED","LOCAL VENDORS-B","","",],
            ["KARACHI BABY CARES","SHAH ALAM VENDOR -C","","",],
            ["KARAM TRADER","LOCAL VENDOR-C","0","0",],
            ["KASHIF BROTHERS (MITCHEELS)","LOCAL VENDOR-C","0","0",],
            ["KASHIF TRADERS (BIOCOS)","LOCAL VENDOR-C","0","0",],
            ["KASHMIR SHAWL","SHAH ALAM VENDOR -C","0","0",],
            ["KAUSAR GHEE MILLS","LOCAL VENDORS-B","0","0",],
            ["KHALID TRADERS DIAPER","LOCAL VENDOR-C","0","0",],
            ["SHEHZAD ENTERPRISES PREV KHALIL BROTHER","LOCAL VENDORS-B","0","0",],
            ["KHALIS GROUP OF INDUSTRIES(OLIO OIL)","LOCAL VENDORS-B","0","0",],
            ["KHAN TRADERS (ROSEPAIR)","LOCAL VENDORS-B","0","0",],
            ["KHAWAJA (GARMENTS)","LOCAL VENDOR-C","0","0",],
            ["Khawaja Medicine Company-Lahore","LOCAL VENDOR-C","0","0",],
            ["KHAWAJA MUJEEB & SONS (AKBARI MANDI)","LOCAL VENDOR-C","","",],
            ["KHAZANA-E-NAIMAT","LOCAL VENDOR-C","","",],
            ["KHOSHGOVAR IMPEX(LOCK&LOCK)","LOCAL VENDOR-C","0","0",],
            ["AB TRADERS (FACE FRESH) PREV KHURRAM TRADERS","LOCAL VENDOR-C","0","0",],
            ["KISAN TRADERS","LOCAL VENDOR-C","","",],
            ["KN ENTERPRISES (KODAK)","LOCAL VENDOR-C","0","0",],
            ["KR&F(ROSE PETAL)","LOCAL VENDORS-B","0","0",],
            ["KROS INTERNATIONAL","LOCAL VENDOR-C","","",],
            ["LAHORE PHARMA PLUS","LOCAL VENDORS-B","0","0",],
            ["LAHORI FOODS","LOCAL VENDOR-C","0","0",],
            ["LASANI CAP HOUSE","SHAH ALAM VENDOR -C","","",],
            ["LIFESTYLE INTERNATIONAL (PVT) LTD.","LOCAL VENDORS-B","0","0",],
            ["LUCKY ENTERPRISES (FRAMESI)","LOCAL VENDOR-C","","",],
            ["LUCKY FASHION GARMENTS","LOCAL VENDOR-C","0","0",],
            ["M A TRADER(MIRA+BANAT+SHOW)","LOCAL VENDOR-C","0","0",],
            ["M B ENTERPRISES","LOCAL VENDORS-B","0","0",],
            ["M H BAIG TRADERS (Pulmonol)","LOCAL VENDOR-C","0","0",],
            ["M I TRADERS (FOOD)SHAHALAM","SHAH ALAM VENDOR-B","0","0",],
            ["INTERNATIONAL BRAND DISTRIBUTORS (SHAADMAN)","LOCAL VENDORS-B","0","0",],
            ["M K TRADERS LEATHER BELTS","LOCAL VENDOR-C","0","0",],
            ["M.AHMAD GARMENTS","LOCAL VENDOR-C","0","0",],
            ["M.AKRAM(BROOM)","LOCAL VENDOR-C","0","0",],
            ["M.N TRADERS (KURLEEZ)","LOCAL VENDOR-C","0","0",],
            ["M.P.H PURSE HOUSE","SHAH ALAM VENDOR -C","","",],
            ["MS ENTERPRISE (VITAL)","LOCAL VENDORS-B","0","0",],
            ["MA TRADER (DITTUS)","LOCAL VENDOR-C","","",],
            ["MAGNUM INTERNATIONAL","LOCAL VENDOR-C","","",],
            ["KAYBEE IMPORTS ENTERPRISES(IGORA COLOUR)","LOCAL VENDORS-B","0","0",],
            ["Makkah Traders (Hall Road)","SHAH ALAM VENDOR -C","","",],
            ["MALIK & SONS SHEZAN JUICE","LOCAL VENDORS-B","0","0",],
            ["MALIK BROTHERS (REEM RICE)","LOCAL VENDOR-C","","",],
            ["MALIK TRADERS","LOCAL VENDOR-C","","",],
            ["MALIK TRADERS (AL-ARIJ)","LOCAL VENDORS-B","0","0",],
            ["MANI BROTHER (LAYS)","LOCAL VENDORS-B","0","0",],
            ["MAQSON DISTRIBUTERS","LOCAL VENDOR-C","","",],
            ["MASTER CUTLERY & KITCHEN WARE","LOCAL VENDOR-C","0","0",],
            ["MATCHLESS FURNITURE","LOCAL VENDOR-C","","",],
            ["MAXCARE INTERNATIONAL (PVT) LTD","LOCAL VENDOR-C","","",],
            ["MEHBOOB GARMENTS & HOUSERY STORE","LOCAL VENDOR-C","0","0",],
            ["MEHBOOB TRADING CO.","LOCAL VENDOR-C","","",],
            ["Mehmood Sons Corporation","LOCAL VENDOR-C","0","0",],
            ["METRON INNOVATIVE(KNORR)","LOCAL VENDOR-C","0","0",],
            ["MIAN EGG TRADERS","LOCAL VENDOR-C","","",],
            ["MILLAT SPORTS","SHAH ALAM VENDOR -C","","",],
            ["MISBAH FROZEN FOODS","LOCAL VENDOR-C","","",],
            ["MITT & COMPANY PVT LTD. (DIPITT)","LOCAL VENDOR-C","","",],
            ["MOBSON MARKETING (COLGATE)","LOCAL VENDORS-B","0","0",],
            ["RIOS (RIVAJ) PREV ISM ENTERPRISES","LOCAL VENDORS-B","0","0",],
            ["MI INTERNATIONAL PREV MOHSIN AND CO","LOCAL VENDORS-B","0","0",],
            ["MOLTYFLEX FOAM","LOCAL VENDOR-C","0","0",],
            ["MOLVI YAQOOB & SONS (DATES)","LOCAL VENDOR-C","0","0",],
            ["MOON BROTHERS (REVO)","LOCAL VENDOR-C","0","0",],
            ["MOOSA TRADERS (ELIT CHOCOLATE)","LOCAL VENDOR-C","0","0",],
            ["MUBEEN TRADERS(MEZAN OIL&GHEE","LOCAL VENDOR-C","0","0",],
            ["MUGHEES TRADERS (SHAH ALAM)","SHAH ALAM VENDOR -C","","",],
            ["MUHAMMAD SHAHZAD (GIFT ITEMS)","LOCAL VENDOR-C","","",],
            ["MULLER & PHIPHES (KERNEL POP)","LOCAL VENDORS-B","0","0",],
            ["MULLER & PHIPPS (PVT) LTD PHARMA","LOCAL VENDOR-C","0","0",],
            ["MULLER & PHIPPS SCOTCH BRITE","LOCAL VENDORS-B","0","0",],
            ["MULLER & PHIPPS(COW & GATE)","LOCAL VENDORS-B","","",],
            ["MULLER & PHIPPS(HEINZ)","LOCAL VENDORS-B","0","0",],
            ["MULTIPLE TRADING HOUSE","LOCAL VENDORS-B","0","0",],
            ["MUMTAZ BROTHERS (COROLI)","LOCAL VENDOR-C","0","0",],
            ["MUMTAZ BROTHERS (BRITANIA)","LOCAL VENDORS-B","0","0",],
            ["MUMTAZ BROTHERS (SASSO/FIGARO)","LOCAL VENDORS-B","0","0",],
            ["MUSA TRADERS ( POLAC CRESCO )","LOCAL VENDOR-C","","",],
            ["BUTT TRADE CO./ BISCONI","LOCAL VENDOR-C","0","0",],
            ["Mussawer Traders Surgical (Lohari)","LOCAL VENDOR-C","","",],
            ["MUSTFA TRADERS PLASTIC CROCKRY","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["MW-MARKETING LU","LOCAL VENDORS-B","0","0",],
            ["N P D (FINS)","LOCAL VENDOR-C","","",],
            ["N P D (PVT.) LTD","LOCAL VENDOR-C","","",],
            ["NABISHA COLLECTION","LOCAL VENDOR-C","","",],
            ["NAFEES SHOPPING BAGS","LOCAL VENDOR-C","","",],
            ["NATIONAL DISTRIBUTION CHANNEL","LOCAL VENDOR-C","","",],
            ["NATIONAL ELECTRONICS (SHAHALAM)","LOCAL VENDOR-C","0","0",],
            ["NATIONAL MARKETING SERVICES (FAUJI)","LOCAL VENDORS-B","0","0",],
            ["NATIONAL TRADERS (KAUSAR GHEE)","LOCAL VENDOR-C","","",],
            ["MUMTAZ TRADERS (ADAMS CHEESE) PREVIOUSLY NAWAZ SONS","LOCAL VENDORS-B","0","0",],
            ["NAZIR TRADERS (HAQUE PLANTERS)","LOCAL VENDOR-C","","",],
            ["NEW BUKHSH TRADERS","LOCAL VENDOR-C","","",],
            ["NEW DOABI TRADERS(OYE HOYE)","LOCAL VENDOR-C","","",],
            ["NEW KHYBER TRADERS (SHAH ALAM)","SHAH ALAM VENDOR-B","0","0",],
            ["NEW LIFE PAPER MART ( SHAH ALAM)","SHAH ALAM VENDOR -C","","",],
            ["NEW LUCKY PLASTIC(SHAH ALAM)","SHAH ALAM VENDOR -C","","",],
            ["NEW MODERN LEATHER STORE","LOCAL VENDOR-C","","",],
            ["NEW UNIQUE PHARMA","LOCAL VENDOR-C","","",],
            ["NIGHAT'S BOUTIQUE","LOCAL VENDORS-B","0","0",],
            ["NOBLE MARKETING(OREAL)","LOCAL VENDORS-B","0","0",],
            ["NOOR ENTERPRISES HARIBO","LOCAL VENDORS-B","0","0",],
            ["NPD (MAYFAIR)","LOCAL VENDOR-C","","",],
            ["NS LEATHER STORE","LOCAL VENDOR-C","","",],
            ["NSON FOODS ( BE SLIM TEA )","LOCAL VENDOR-C","","",],
            ["NUR ENTERPRISES (RECKIT)","LOCAL VENDORS-B","0","0",],
            ["OPAL DISTRIBUTOR(BOLDBODY SPRAY)","LOCAL VENDORS- NON FOOD ","0","0",],
            ["OPTIMUS CREST PRIVATE LTD.(QARSHI)","LOCAL VENDORS-B","0","0",],
            ["PAARIS DISTRIBUTORS PHARMA LAHORE","LOCAL VENDOR-C","","",],
            ["PAINDOO PRODUCT (HONEY)","LOCAL VENDOR-C","","",],
            ["PAK INTERNATIONAL(KARACHI)","SHAH ALAM VENDOR -C","","",],
            ["PAK NATIONAL DISTRIBUTION HOUSE","LOCAL VENDORS-B","0","0",],
            ["PAK ORGANICO (LECHE MILK)","LOCAL VENDOR-C","","",],
            ["ASIAN DAIRIES (PAK BUTTER) PREV PAK TRADERS","LOCAL VENDORS-B","0","0",],
            ["PAKISTAN FRUIT JUNICE COMPANY(HICO)","LOCAL VENDORS-B","0","0",],
            ["PAKISTAN VACCINE HOUSE","LOCAL VENDOR-C","","",],
            ["PARADISE AGENCIES","LOCAL VENDOR-C","","",],
            ["Paramount Distributor (Tiger)","LOCAL VENDOR-C","","",],
            ["PARAZELSUS PAKISTAN (PVT) LTD. PHARMA","LOCAL VENDORS-B","0","0",],
            ["PERFUME PALACE","LOCAL VENDOR-C","","",],
            ["Platinum Pharmaceuticals (Pvt) Ltd.","LOCAL VENDOR-C","","",],
            ["PREMIER AGENCIES (ABBOT)","LOCAL VENDORS-B","0","0",],
            ["PREMIER AGENCIES (CADBURY)","LOCAL VENDORS-B","0","0",],
            ["PREMIER AGENCIES (DEER)","LOCAL VENDORS-B","0","0",],
            ["PREMIER AGENCIES (FALAK RICE)","LOCAL VENDORS-B","0","0",],
            ["PREMIER AGENCIES (GSK)","LOCAL VENDORS-B","0","0",],
            ["PREMIER AGENCIES (HIMALAYA)","LOCAL VENDORS-B","0","0",],
            ["PREMIER AGENCIES B-PARLOR","LOCAL VENDORS-B","0","0",],
            ["Premier Agencies PHARMA","LOCAL VENDORS-B","","",],
            ["PREMIER AGENCIES(SHIELD)","LOCAL VENDORS-B","0","0",],
            ["PREMIER AGENCIES(SUNRIDGE FLOUR)","LOCAL VENDORS-B","0","0",],
            ["PRIME CANDLES","LOCAL VENDOR-C","","",],
            ["PRIME MARKETING (HALEEB)","LOCAL VENDOR-C","","",],
            ["PRODUCT MARKETING SYSTEMS","LOCAL VENDOR-C","","",],
            ["QADRI BROTHERS (SHEZAN JAM) ","LOCAL VENDORS-B","0","0",],
            ["QUALITY STORE SHAHALAM","SHAH ALAM VENDOR -C","0","0",],
            ["QUICK FOOD INDUSTRIES(MON SALWA)","LOCAL VENDORS-B","0","0",],
            ["R I TRADERS","LOCAL VENDOR-C","0","0",],
            ["R.A TRADER KALA KOLA","LOCAL VENDOR-C","0","0",],
            ["R.T GENERAL STORE","LOCAL VENDOR-C","","",],
            ["RAAZIQ MARKETING & MANAGEMENT","LOCAL VENDOR-C","","",],
            ["RACHNA MARKETING","LOCAL VENDORS-B","0","0",],
            ["RAFIQUE TRADERS (YOUNGS)","LOCAL VENDORS-B","0","0",],
            ["RAIM ENTERPRISES","SHAH ALAM VENDOR -C","","",],
            ["RAINBOW CASH & CARRY (ISLAMABAD)","LOCAL VENDOR-C","","",],
            ["RAINBOW CASH & CARRY EME RECEIVABLE","LOCAL VENDOR-C","","",],
            ["RAINBOW CASH & CARRY WAPDA TOWN (PAYABLE)","LOCAL VENDOR-C","","",],
            ["RAMZAN BUTT SHAHALM","SHAH ALAM VENDOR -C","","",],
            ["RAPID DISTRIBUTORS (OPA FRIES)","LOCAL VENDORS-B","0","0",],
            ["RAZA LIONS","SHAH ALAM VENDOR -C","","",],
            ["RAZA TRADERS(FOOD NET)","LOCAL VENDORS-B","0","0",],
            ["RAZI SONS (FRUIT TREE JAM)","LOCAL VENDORS-B","0","0",],
            ["REHMAN CORPORATION","LOCAL VENDOR-C","","",],
            ["REHMAN DISTRIBUTORS","LOCAL VENDOR-C","","",],
            ["Rehman Knitting","LOCAL VENDOR-C","","",],
            ["REHMAT FLOUR MILLS","LOCAL VENDOR-C","","",],
            ["RETAIL SOLUTION","LOCAL VENDORS-B","0","0",],
            ["MUMTAZ DISTRIBUTION NETWORK (TAPAL)","LOCAL VENDORS-B","0","0",],
            ["RIAZ & SONS (HINZ POINT)","LOCAL VENDOR-C","","",],
            ["LOTTE AKHTAR BEVERAGES (PEPSI)","LOCAL VENDORS-B","0","0",],
            ["RICE WORLD (AL-GHAZAAL RICE)","LOCAL VENDOR-C","","",],
            ["RITZY PVT LTD (KING KASHMIT TEA)","LOCAL VENDOR-C","","",],
            ["ROOTS DISTRIBUTION (GODREJ)","LOCAL VENDOR-C","","",],
            ["FADI  HERBS CO. PREV ROYAL LEAF INTERNATIONAL","LOCAL VENDORS-B","0","0",],
            ["S M AGENCIES","LOCAL VENDOR-C","","",],
            ["SADIQ MAKETING (CANBEBE) PREV S S ENTERPRISES","LOCAL VENDORS-B","0","0",],
            ["S&H MARKETING (TOMAS)","LOCAL VENDOR-C","","",],
            ["S.H FASHION (HEERA GARMENTS)","LOCAL VENDOR-C","","",],
            ["S.I TRADERS (PERFUMES)","SHAH ALAM VENDOR -C","0","0",],
            ["S.K GARMENTS","LOCAL VENDOR-C","","",],
            ["S.N MARKETING (CHOICE HAIR ACCESSORIES )","LOCAL VENDOR-C","","",],
            ["S.R TRADERS (SUFI SURF)","LOCAL VENDOR-C","","",],
            ["SAAD ENTERPRISES MILK","LOCAL VENDOR-C","","",],
            ["SABA ENTERPRISES WATCH","SHAH ALAM VENDOR -C","","",],
            ["SABIR POULTRY (PVT) LTD.","LOCAL VENDORS-B","0","0",],
            ["SACA PLUS (CAR ACCESSORIES)","LOCAL VENDOR-C","0","0",],
            ["SADAT PHARMA","LOCAL VENDOR-C","","",],
            ["SADIQ POULTRY (PVT) LTD","LOCAL VENDORS-B","0","0",],
            ["SAIBAN TRADERS SHANGRILA","LOCAL VENDORS-B","0","0",],
            ["SAJID JEANS HOUSE","LOCAL VENDOR-C","","",],
            ["SALMAN TRADERS (SHAHALAM)","SHAH ALAM VENDOR -C","","",],
            ["SAMAR SHAMSI TOWEL HOUSE","LOCAL VENDOR-C","","",],
            ["PALZAR ENTERPRISES PREV SAMSON ENTERPRISE","LOCAL VENDOR-C","0","0",],
            ["SANA PAPER (RISEN HYGIENIC JUMBO)","LOCAL VENDOR-C","0","0",],
            ["SANA SHALL AZAM MARKET","LOCAL VENDOR-C","","",],
            ["SEASONS FOOD (MENU)","LOCAL VENDOR-C","","",],
            ["SEASONS RICE (PVT) LTD","LOCAL VENDOR-C","","",],
            ["SEVEN STAR GARMENTS","LOCAL VENDOR-C","","",],
            ["SHA TRADERS (OMYPOP)","LOCAL VENDOR-C","","",],
            ["SHABAAN DISTRIBUTOR (LUBNA'S WAX)","LOCAL VENDOR-C","","",],
            ["SHAFEE ULLAH (SMOCKERS)","SHAH ALAM VENDOR -C","","",],
            ["SHAFIQUE TRADERS (BIOMILL)","LOCAL VENDOR-C","","",],
            ["SHAHAN DISTRIBUTORS (RIMMEL)","LOCAL VENDOR-C","","",],
            ["SHAHBAZ ENTERPRISES (KIDCO)","LOCAL VENDOR-C","","",],
            ["RUHABA IMPEX PREV SHAHID JEWELLERY (KARACHI)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["SHAHID RABBANI CALCULATORS","LOCAL VENDOR-C","","",],
            ["SHAHID SHAWLS","LOCAL VENDOR-C","","",],
            ["SHAHID SONS (DIPPO)","LOCAL VENDORS-B","0","0",],
            ["SHAHZAD CLOCK HOUSE","SHAH ALAM VENDOR -C","","",],
            ["SHAHZAD DAIRES(BUTTER)","LOCAL VENDORS-B","0","0",],
            ["M.Y.T TRADERS(OLIO)","LOCAL VENDOR-C","0","0",],
            ["SHAKEEL GARMENTS","LOCAL VENDOR-C","","",],
            ["SHAKEEL MEDICINE COMPANY","LOCAL VENDOR-C","","",],
            ["SHAKOOR HOSIERY MERCHANT (HEINZ U/G)","LOCAL VENDOR-C","","",],
            ["SHALIMAR GARMENTS","LOCAL VENDOR-C","","",],
            ["SHAMSI MARKETING SERVICES","LOCAL VENDORS-B","0","0",],
            ["SHAN-E-MARKETING","LOCAL VENDOR-C","","",],
            ["SHARIF MILK PRODUCTS","LOCAL VENDORS-B","0","0",],
            ["SHARJEEL TRADERS SEASONS","LOCAL VENDOR-C","","",],
            ["SHE COSMATIC (DERMACOS)","LOCAL VENDOR-C","","",],
            ["SHEIKH BROTHERS (SUPER PHENYLE)","LOCAL VENDORS-B","0","0",],
            ["ISM ENTERPRISES PREV SHEIKH JAVED & SONS","SHAH ALAM VENDOR-B","0","0",],
            ["SHEIKH JAVED & SONS (UNDERGARMENTS)","SHAH ALAM VENDOR -C","","",],
            ["KARIM CONTAINERS (PLASTIC CROCKERY)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["SHINWARI GLOBAL ENTERPRISES","SHAH ALAM VENDOR -C","0","0",],
            ["SHINWARI INTERNATIONAL CO.","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["SHUJABAD AGRO INDUSTRIES (PVT) LTD (EVA OIL)","LOCAL VENDORS-B","0","0",],
            ["RS&F (NESTLE POWDER) PREV SIGMA DIST ","LOCAL VENDORS-B","0","0",],
            ["RS&F (NESTLE LIQUID) PREV SIGMA DIST","LOCAL VENDORS-B","0","0",],
            ["SIGMA DISTRIBUTOR (PVT) LTD ( RED RUMI)","LOCAL VENDORS-B","0","0",],
            ["SIGMA DISTRIBUTORS(PVT) LTD(PAKOLA)","LOCAL VENDORS-B","0","0",],
            ["SS TRADINGS (WIPERS) PREV SITARA WIPERS","LOCAL VENDORS-B","0","0",],
            ["SOLUTION INN GLOBAL PARTNER","LOCAL VENDOR-C","","",],
            ["EMADULLAH & BROTHERS (TRUST) PREV SPOT","LOCAL VENDORS-B","0","0",],
            ["SPOT DISTRIBUTERS (HILAL)","LOCAL VENDOR-C","","",],
            ["SPOT DISTRIBUTOR (BRITANNIA)","LOCAL VENDOR-C","0","0",],
            ["SQUARES DISTRIBUTION (PHARMA)","LOCAL VENDOR-C","","",],
            ["STAR TRADING (SHAH ALAM)","SHAH ALAM VENDOR -C","","",],
            ["THREAD MASTER PREV STILL UNDER GARMENTS","LOCAL VENDORS-B","0","0",],
            ["SUFI ARSHAD (BROOM)","LOCAL VENDOR-C","","",],
            ["SULTAN TRADERS (SHAH ALAM)","SHAH ALAM VENDOR-B","0","0",],
            ["SUPER LEATHER BELT","LOCAL VENDOR-C","","",],
            ["SWIFT MARKTING (PEEK FREANS)","LOCAL VENDORS-B","0","0",],
            ["SWIFTLINK DISTRIBUTION","LOCAL VENDOR-C","","",],
            ["HASSAN CORPORATION (HASSAN RICE)","LOCAL VENDORS-B","0","0",],
            ["SYED BROTHERS(HARMONY)","LOCAL VENDOR-C","","",],
            ["TAHIR TRADERS (SALMAN JAM)","SHAH ALAM VENDOR -C","","",],
            ["TALAL & COMPANY 2 (YOUNGS)","LOCAL VENDORS-B","0","0",],
            ["TALHA TRADERS (CAMELION)","LOCAL VENDORS-B","0","0",],
            ["HASSAN TRADERS PREV TALHA TRADERS (GOREY)","LOCAL VENDOR-C","0","0",],
            ["TARIQ BROTHERS (HASHMI) SURMA","LOCAL VENDOR-C","","",],
            ["TARIQ BROTHER'S(SHAHALAM)","LOCAL VENDOR-C","","",],
            ["Tariq Saleem Drug Agency (Lohari)","LOCAL VENDOR-C","","",],
            ["TARSEEL PVT (ENERGIZER)","LOCAL VENDORS-B","0","0",],
            ["TARSEEL(PVT)LTD","LOCAL VENDORS-B","0","0",],
            ["TARSEEL(PVT.LTD(SPONTEX)","LOCAL VENDORS-B","0","0",],
            ["TEE ACH LEATHER KARACHI (LEATHER WALLET)","LOCAL VENDOR-C","","",],
            ["TEHZEEB TRADERS (MOTHER CARE)","LOCAL VENDOR-C","","",],
            ["TEX-HOME COTT N TERRY","LOCAL VENDOR-C","","",],
            ["THAI CENTER LAHORE (CROCKERY)","SHAH ALAM VENDOR -C","0","0",],
            ["The Vitamin Company Pharma","LOCAL VENDOR-C","","",],
            ["THE WOOD SMITH","LOCAL VENDOR-C","","",],
            ["THUMBS UP DISTRIBUTION  (DELICIO) ","LOCAL VENDORS-B","0","0",],
            ["TOPS FOODS & BEVERAGES","LOCAL VENDOR-C","","",],
            ["IMKA TRDAERS PREV TOUHEED TRADERS","LOCAL VENDORS-B","0","0",],
            ["TOYS & TOYS SHAHALAM","SHAH ALAM VENDOR -C","0","0",],
            ["TRADE LINKS NURPUR MILK","LOCAL VENDORS-B","0","0",],
            ["TRADE WORLD MARKETING SHAHALAM","SHAH ALAM VENDOR-B","0","0",],
            ["NUR ENTERPRISES (DABUR)   PREVIOUSLY TRADING RESOURCE","LOCAL VENDORS-B","0","0",],
            ["TRIPPLE A TRADERS (INOVATIVE)","LOCAL VENDOR-C","","",],
            ["IDL MARKETING (DOCTOR PASTE)","LOCAL VENDORS-B","0","0",],
            ["UA GARMENTS","LOCAL VENDOR-C","","",],
            ["SHANNS COSMETICS & CHEMICALS (SOFT TOUCH) PREV UD TRADERS ","LOCAL VENDORS-B","0","0",],
            ["UDL DISTRIBUTION (PVT) LTD GATSBY+NEUTROGENA","LOCAL VENDORS-B","0","0",],
            ["UDL DISTRIBUTOR (PVT) LTD. MORINAGA","LOCAL VENDORS-B","0","0",],
            ["TUFAIL SON (SHAHALAM) PREV UK TRADERS","SHAH ALAM VENDOR-B","0","0",],
            ["UMAR TRADER SHAHALAM","LOCAL VENDOR-C","","",],
            ["UMER TRADERS (SHAHALAM)","LOCAL VENDOR-C","","",],
            ["UNIQUE ENTERPRISES","LOCAL VENDOR-C","","",],
            ["UNIQUE PHARMACY","LOCAL VENDOR-C","","",],
            ["UNITED BRAND LIMITED (OVALTINE)","LOCAL VENDORS-B","0","0",],
            ["UNITED BRANDS (COMPLAN)","LOCAL VENDOR-C","","",],
            ["UNITED BRANDS (KELLOGGS)","LOCAL VENDORS-B","0","0",],
            ["UNITED BRANDS (PVT) LIMITED","LOCAL VENDORS-B","0","0",],
            ["UNITED BRANDS LIMITED (JOHNSON)","LOCAL VENDORS-B","0","0",],
            ["UNITED DAIRY FARMS(PAK PURE)","LOCAL VENDORS-B","0","0",],
            ["UNITED KING FOODS (PVT.) LTD.","LOCAL VENDOR-C","","",],
            ["URBAN KIDS","LOCAL VENDOR-C","","",],
            ["ULTIMATE WORLDWIDE (ELMORE) PREV S.M SHAHID & SONS ","LOCAL VENDORS-B","0","0",],
            ["USMAN TRADERS (RASSASI)","SHAH ALAM VENDOR -C","","",],
            ["VATANI TRADING CO.","LOCAL VENDORS-B","0","0",],
            ["VENTURE TRADING ENTERPRISES","LOCAL VENDORS-B","0","0",],
            ["Vikor Enterprises Pvt Ltd Pharma","LOCAL VENDOR-C","","",],
            ["VISION ENTERPRISES (STEEN SOFT TISSUES)","LOCAL VENDOR-C","","",],
            ["W.K ENTERPRISES (PEAK FREANS)","LOCAL VENDOR-C","","",],
            ["W.R DISTRIBUTION","LOCAL VENDOR-C","","",],
            ["WAFA ENTERPRISES (DES CHEF)","LOCAL VENDOR-C","","",],
            ["WAFA ENTERPRISES (TIFFANY)","LOCAL VENDORS-B","0","0",],
            ["WAFA ENTERPRISES(ME-O-CAT)","LOCAL VENDORS-B","0","0",],
            ["WAHDAT POULTRY FARM","LOCAL VENDORS-B","0","0",],
            ["WAHEED CAP HOUSE","LOCAL VENDOR-C","","",],
            ["WALEED GARMENTS","LOCAL VENDOR-C","","",],
            ["WARSI & SONS (STABILO)","LOCAL VENDOR-C","","",],
            ["SATTAR ELECTRONICS (WESTPOINT)","LOCAL VENDORS-B","0","0",],
            ["H&H DISTRBUTION NETWORK (KINZA)","LOCAL VENDOR-C","0","0",],
            ["WISTO MELAMINE CROKERY","LOCAL VENDOR-C","","",],
            ["WR DISTRIBUTION SHEZAN","LOCAL VENDOR-C","","",],
            ["YASEEN TOYS(SHAHALAM)","LOCAL VENDOR-C","0","0",],
            ["RAFIQ TRADERS (GANJ SUGAR) PREV YASIR BROTHERS","LOCAL VENDOR-C","0","0",],
            ["YOUNAS SHALL HOUSE","LOCAL VENDOR-C","","",],
            ["YOUSAF SCHOOL BAG","SHAH ALAM VENDOR -C","","",],
            ["Z.J.AGENCIES(LAZIZA)","LOCAL VENDORS-B","0","0",],
            ["Z.R ENTERPRISES(FAY TISSUE)","LOCAL VENDOR-C","","",],
            ["ZAFAR TRADERS UNDER GARMENTS","SHAH ALAM VENDOR -C","0","0",],
            ["Zain Marketing (INSTUM)","LOCAL VENDOR-C","0","0",],
            ["ZAIN TRADER (TIGER)","LOCAL VENDOR-C","","",],
            ["ZAKIR BROTHERS","LOCAL VENDOR-C","","",],
            ["ZAKIR KHAN BMK TOWEL","LOCAL VENDOR-C","","",],
            ["AMK ENTERPRISES (KORNEEZ) ZAS TRADERS ","LOCAL VENDORS-B","0","0",],
            ["ZK TRADERS (DUE CREAM)","LOCAL VENDOR-C","","",],
            ["ZNZ BRANDS SHAHALAM","SHAH ALAM VENDOR-B","0","0",],
            ["IDARA-AL-FATEHA","LOCAL VENDOR-C","0","0",],
            ["KHALIL & CO. PREV FRUIT & VEGITABLE - VENDOR","OUTSOURCED VENDOR","0","0",],
            ["HI-G FOODS PREV MEAT VENDOR","OUTSOURCED VENDOR","0","0",],
            ["LADIES UNDERGARMENTS- VENDOR","OUTSOURCED VENDOR","0","0",],
            ["GARMENTS VENDOR","OUTSOURCED VENDOR","0","0",],
            ["WASEEM PLASTIC","LOCAL VENDOR-C","0","0",],
            ["M/S OSAMA AGENCIES (COOL & COOL)","LOCAL VENDORS-B","0","0",],
            ["110 TRADERS (SHIRIN ASAL)","LOCAL VENDOR-C","0","0",],
            ["GOLDEN COTTAGE CHEESE","LOCAL VENDOR-C","0","0",],
            ["BETTER HOME CROCKERY (MELAMINE) PREV SHAN & CO.","LOCAL VENDORS-B","0","0",],
            ["PHARMACY VENDOR","OUTSOURCED VENDOR","0","0",],
            ["FATEH GARH TRADERS","LOCAL VENDOR-C","0","0",],
            ["ASKRI XI TRADERS","LOCAL VENDOR-C","0","0",],
            ["BISMILLAH DISTRIBUTION(DEW DROP)","LOCAL VENDOR-C","0","0",],
            ["MATCHLESS TASTE (UNIQUE NIMKO)","LOCAL VENDOR-C","0","0",],
            ["QUALITY TRADERS (PLASTIC BAGS)","LOCAL VENDOR-C","0","0",],
            ["PREMIER TRADING COMPANY (DADI JAN)","LOCAL VENDOR-C","0","0",],
            ["CHAKWAL TRADERS","LOCAL VENDOR-C","0","0",],
            ["DAWN FROZEN FOODS COMPANY PVT .LIMITED","LOCAL VENDORS-B","0","0",],
            ["MH ENTERPRISES","LOCAL VENDOR-C","0","0",],
            ["LIPCARA (DARMA SHINE)","LOCAL VENDORS-B","30","0",],
            ["AZHAR ENTERPRISES (CAT FOOD)","LOCAL VENDOR-C","0","0",],
            ["CHANNEL LINK (CANBEBE)","LOCAL VENDORS-B","0","0",],
            ["CONNECT MARKETING SERVICES (SHANGRILA)","LOCAL VENDORS-B","0","0",],
            ["AA9 INTERNATIONAL (HABIB OIL & GHEE)","LOCAL VENDORS-B","0","0",],
            ["FAZAL TRADERS (MITCHELL'S)","LOCAL VENDORS-B","0","0",],
            ["M.A.H TRADERS (CHIKO)","LOCAL VENDOR-C","0","0",],
            ["MAHARANI CONE MEHNDI","LOCAL VENDOR-C","0","0",],
            ["CH. M. YASEEN (PEPSI)","LOCAL VENDOR-C","0","0",],
            ["ICON INTERNATIONAL (DERMACOS)","LOCAL VENDOR-C","0","0",],
            ["ROOTS NATURAL TRADERS","LOCAL VENDORS-B","0","0",],
            ["KN ENTERPRISES /(CANBEBE)","LOCAL VENDORS-B","0","0",],
            ["BILAL BROTHERS (MOIZ FOODS)","LOCAL VENDORS-B","0","0",],
            ["EHY INTERNATIONAL (RIGEL OIL)","LOCAL VENDOR-C","0","0",],
            ["MUMTAZ DISTRIBUTION (HAPPY COW)","LOCAL VENDOR-C","0","0",],
            ["RB TRADERS INTERNATIONAL (CROKERY)","SHAH ALAM VENDOR -C","0","0",],
            ["A TRADERS (TOYS & TOYS)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["AL-QAIM TRADERS","LOCAL VENDOR-C","0","0",],
            ["AL-WASAY DISTRIBUTION (OPA FRIES)","LOCAL VENDORS-B","0","0",],
            ["AA FOODS (CHO CHO) PREV BUTT BROTHERS","LOCAL VENDORS-B","0","0",],
            ["FANTASIA FLORIST (ARTIFICIAL PLANTS)","SHAH ALAM VENDOR -C","0","0",],
            ["FATIMA TRADERS PREV 3A PAKISTAN ","LOCAL VENDORS-B","0","0",],
            ["AI ENTERPRISES (NURPUR)","LOCAL VENDORS-B","0","0",],
            ["JTC ENTERPRISES (THI CENTER)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["FAZAL TRADERS (BIO AMLA)","LOCAL VENDORS-B","0","0",],
            ["PREMIER SALES (IGORA COLOUR)","LOCAL VENDORS-B","0","0",],
            ["FAROQI BROTHERS (SUFI GHEE)","LOCAL VENDORS-B","0","0",],
            ["RAVI MARKETING (PHILLIPS)","LOCAL VENDOR-C","0","0",],
            ["WILMAX PAKISTAN (CROCKERY)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["AA9 INTERNATIONAL (PVT.) LTD (DIPPIT)","LOCAL VENDORS-B","0","0",],
            ["FATIMA ENTERPRISES (MOULINEX ELECTRONICS)","SHAH ALAM VENDOR -C","0","0",],
            ["IDL MARKETING (OLIVIA)","LOCAL VENDORS-B","0","0",],
            ["BUTT TRADERS (GOLDEN PEARL)","LOCAL VENDOR-C","0","0",],
            ["KHOSHGOVAR FOODS (ADAM)","LOCAL VENDORS-B","0","0",],
            ["SS TRADER (SHAHALAM)","SHAH ALAM VENDOR-B","0","0",],
            ["AME TRADERS (HOMEISH INTERIOR)","LOCAL VENDORS-B","0","0",],
            ["MYCELL TECHNOLOGIES","LOCAL VENDOR-C","0","0",],
            ["vENDOR","LOCAL VENDORS-B","0","0",],
            ["S.M RICE TRADER (HABIB OIL)","LOCAL VENDORS-B","0","0",],
            ["PRIME ALLIANCE (NURPUR) PREV LALA G TRADERS","LOCAL VENDORS-B","0","0",],
            ["ISHMAM CO. (SHAHALAM)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["UNICORN INTERNATIONAL (BAGS)","LOCAL VENDORS-B","0","0",],
            ["KASHIF BROTHERS (NURPUR)","LOCAL VENDORS-B","0","0",],
            ["SAEED & SONS (SHAHALAM)","SHAH ALAM VENDOR-B","0","0",],
            ["M.N ENTERPRISES (MAMIA) PREV AMNA ENTERPRISES ","LOCAL VENDORS-B","0","0",],
            ["RIZWAN TRADE EXPERT (DIPPIT)","LOCAL VENDORS-B","0","0",],
            ["NAVEED ENTERPRISES (MAMIA)","LOCAL VENDORS-B","0","0",],
            ["S.S ENTERPRISES","SHAH ALAM VENDOR-B","0","0",],
            ["MAKKAH FRAMING CENTER","SHAH ALAM VENDOR -C","0","0",],
            ["CARPET -VENDOR","OUTSOURCED VENDOR","0","0",],
            ["FURNITURE- VENDOR","OUTSOURCED VENDOR","0","0",],
            ["BISMILLAH CORPORATION (BEDDING)","LOCAL VENDOR-C","0","0",],
            ["ASHAL ENTERPRISES (SHAHALAM)","SHAH ALAM VENDOR -C","0","0",],
            ["LADIES SUIT-VENDOR","OUTSOURCED VENDOR","0","0",],
            ["PREMIER SALES (RECKIT)","LOCAL VENDORS-B","0","0",],
            ["HAF ENTERPRISES (CARPET) PREV AHMED BROTHERS ","LOCAL VENDORS-B","0","0",],
            ["NUR ENTERPRISES (BLUE BAND)","LOCAL VENDOR-C","0","0",],
            ["STLTH INTERNATIONAL","LOCAL VENDOR-C","0","0",],
            ["SENQUA HEALTHCARE (KURLEEZ) PREV ZAHID TRADER","LOCAL VENDORS-B","0","0",],
            ["AL SHAHEER CORPRATION (CHEF ONE)","LOCAL VENDORS-B","0","0",],
            ["Adf","LOCAL VENDOR-C","","877327",],
            ["RYZEN ENTERPRISES (DABUR)","LOCAL VENDORS-B","0","0",],
            ["FOREIGN TRADING COMPANY (CROCKERY)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["POLYSET INDUSTRIES PVT LTD PREV HADI INTERNATIONAL TRADING (PLASTIC CROCKERY)","SHAH ALAM VENDOR-B","0","0",],
            ["WASEEM BROTHERS (SUFI SOAP)","LOCAL VENDORS-B","0","0",],
            ["WASEEM BROTHERS (EZIGRIP)","LOCAL VENDORS-B","0","0",],
            ["AL ZAMIN TRADER (LAZIZA)","LOCAL VENDORS-B","0","0",],
            ["ABDUL WAHAB & SONS (SHAH ALAM)","SHAH ALAM VENDOR-B","0","0",],
            ["SHER-E-RABBANI (SHEZAN JAM)","LOCAL VENDORS-B","0","0",],
            ["I.K TRADERS (BREEO)","LOCAL VENDORS-B","0","0",],
            ["ROOMI POULTRY (VITA EGG) PREV SHAZIA TRADING CO.","LOCAL VENDORS-B","0","0",],
            ["MADNI TRADERS (CARE)","LOCAL VENDORS-B","0","0",],
            ["A4 TRADER (ROSE PETAL)","LOCAL VENDORS-B","0","0",],
            ["YKR ENTERPRISES","LOCAL VENDORS-B","0","0",],
            ["AL-IMRAN TRADING (SUPER CRISP)","LOCAL VENDORS-B","0","0",],
            ["SHAHID & FOOD CO.","LOCAL VENDORS-B","0","0",],
            ["NETWORK MARKETERS (FAUJI CEREEAL)","LOCAL VENDORS-B","0","0",],
            ["ABBAS TRADERS (MARIOS)","LOCAL VENDORS-B","0","0",],
            ["SR TRADERS (QARSHI)","LOCAL VENDORS-B","0","0",],
            ["M.N ENTERPRISES (SALMAN JAM)","LOCAL VENDORS-B","0","0",],
            ["MATTOO CORPORATION (BRITANNIA)","LOCAL VENDORS-B","0","0",],
            ["SARWANA & SOHZSIHM (ENGLISH PASTE)","LOCAL VENDORS-B","0","0",],
            ["MASOOD BROTHERS (BOLD BODY SPRAY)","LOCAL VENDORS-B","0","0",],
            ["IDEAL TRADERS (EZIGRIP)","LOCAL VENDORS-B","0","0",],
            ["R.A TRADERS (SAMSOL)","LOCAL VENDORS-B","0","0",],
            ["CHANNEL LINK (BISCONI)","LOCAL VENDORS-B","0","0",],
            ["AFZAL TRADER (QARSHI PHARMACY) PREV SAI TRADERS ","LOCAL VENDORS-B","0","0",],
            ["MAZ ENTERPRISES (KORNEZ)","LOCAL VENDORS-B","0","0",],
            ["ROYAL FRIENDS MARKETING (SALMAN JAM)","LOCAL VENDORS-B","0","0",],
            ["UMER TRADERS (QARSHI)","LOCAL VENDORS-B","0","0",],
            ["ZS TRADERS (MITCHELL'S) PREV YOUSAF DISTRIBUTORS ","LOCAL VENDORS-B","0","0",],
            ["FATIMA DISTRIBUTION NETWORK (TOYO NASIC)","LOCAL VENDORS-B","0","0",],
            ["HASHAM FOOD","LOCAL VENDORS-B","0","0",],
            ["HUSEIN SUHAR MILLS LIMITED","LOCAL VENDORS-B","0","0",],
            ["SKA INNOVATION (FOOD NET)","LOCAL VENDORS-B","0","0",],
            ["TALHA MUJTABA TRADER (LAZIZA)","LOCAL VENDORS-B","0","0",],
            ["GUL EDIBLE OIL","LOCAL VENDORS-B","0","0",],
            ["FINE BABY CYCE","OUTSOURCED VENDOR","0","0",],
            ["MERCATOR CORP (IPSA)","LOCAL VENDORS-B","0","0",],
            ["FA ENTERPRISE (BECUTE)","LOCAL VENDORS-B","0","0",],
            ["SUFI ENTERPRISES (SUFI SOAP)","LOCAL VENDORS-B","0","0",],
            ["UNION MARKETING (SUPER CRISP)","LOCAL VENDORS-B","0","0",],
            ["MA ENTERPRISES (GOOD MILK)","LOCAL VENDORS-B","0","0",],
            ["ASIAN ENTERPRISES (HAIR BRUSH)","LOCAL VENDORS-B","0","0",],
            ["ALI GOHAR & CO. (SAVANNAH SOAP)","LOCAL VENDORS-B","0","0",],
            ["RED DISTRIBUTORS (OLIVOLA)","LOCAL VENDORS-B","0","0",],
            ["HUL ENTERPRISES (BAGS)","LOCAL VENDORS-B","0","0",],
            ["M. HADEED TRADER (MANIA)","LOCAL VENDORS-B","0","0",],
            ["ROYAL CART (KINGTOX)","LOCAL VENDORS-B","0","0",],
            ["NAEEM TRADERS (SHIELD)","LOCAL VENDORS-B","0","0",],
            ["NAWAZ BROTHERS (CANOLIVE)","LOCAL VENDOR-C","0","0",],
            ["EFF DEE WATER (NOVA GLASS)","LOCAL VENDORS-B","0","0",],
            ["ZAFAR AMIN TEXTILE (SHOPING BAGS)","LOCAL VENDORS-B","0","0",],
            ["MAMTA ENTERPRISES (SHAHALAM)","SHAH ALAM VENDOR-B","0","0",],
            ["TANDLIANWALA SUGAR MILLS","LOCAL VENDOR-C","0","0",],
            ["CAPCON ENTERPRISES (SALMAN JAM)","LOCAL VENDORS-B","0","0",],
            ["JUGNU TECH (PVT.) LTD. (MILK FIELD)","LOCAL VENDORS-B","0","0",],
            ["ELHAI TRADERS PREV (DOCTOR TOOTHPASTE) ZSJ ENTERPRISES ","LOCAL VENDORS-B","0","0",],
            ["3A MARKETING NETWORK (SHAH ALAM)","SHAH ALAM VENDOR-B","0","0",],
            ["SADAAT TRADERS (NATURELLE)","LOCAL VENDORS-B","0","0",],
            ["BIOCOS INTERNATIONAL (PVT.) LTD","LOCAL VENDORS-B","0","0",],
            ["AL REHMAN TRADING COMPANY (MARIOS)","LOCAL VENDORS-B","0","0",],
            ["BAKERY VENDOR","OUTSOURCED VENDOR","0","0",],
            ["AL-MUTWAKAL TRADING COMPANY (UNILEVER)","LOCAL VENDORS-B","0","0",],
            ["SAJID TRADING (EZI COLOUR)","LOCAL VENDOR-C","0","0",],
            ["ELIXIR MARKETING & DISTRIBUTION (KOLESTON COLOR)","LOCAL VENDORS-B","0","0",],
            ["SHOES VENDOR","OUTSOURCED VENDOR","0","0",],
            ["UNIVERSAL HOUSE OF TRADES","LOCAL VENDOR-C","0","0",],
            ["KS ENTERPRISES (SHAH ALAM)","SHAH ALAM VENDOR-B","0","0",],
            ["KAW COSMESTICS (BLACK ROSE)","LOCAL VENDOR-C","0","0",],
            ["BRANDS UNLIMITED (PVT) LTD","LOCAL VENDOR-C","0","0",],
            ["KING BAVARGE","LOCAL VENDOR-C","0","0",],
            ["KHAN & KHAN LAHORE (SHANGRILA)","LOCAL VENDORS-B","0","0",],
            ["CHOUDRY DISTRIBUTOR (COLGATE-P)","LOCAL VENDORS-B","0","0",],
            ["NOOR FATIMA ENTERPRISES (COTT N COLORS) ","LOCAL VENDORS-B","0","0",],
            ["SIGMA DISTRIBUTORS (PVT) LTD BBM","LOCAL VENDORS-B","0","0",],
            ["CAMEL STATIONERY","SHAH ALAM VENDOR -C","0","0",],
            ["ALI BROTHER GOREY ","LOCAL VENDOR-C","0","0",],
            ["BILAL & SONS HABIB OIL","LOCAL VENDORS-B","0","0",],
            ["S & H MARKETING DES CHEF","LOCAL VENDOR-C","0","0",],
            ["AHMED BROTHERS NATURELLE OIL","LOCAL VENDOR-C","0","0",],
            ["HASSAN TRADERS BROOM","LOCAL VENDOR-C","0","0",],
            ["AL-SAEED TRADING CO. (4U2 COSMETICS)","LOCAL VENDORS-B","0","0",],
            ["AL-SAEED TRADING CO (SIVANNA COLORS)","LOCAL VENDORS-B","0","0",],
            ["VERTEX FOODS A DISTRIBUTION (AL MARAI)","LOCAL VENDOR-C","0","0",],
            ["FAIZAN ENTERPRISES (CHIKO)","LOCAL VENDOR-C","0","0",],
            ["SIGMA DISTRIBUTORS (PVT) LTD UNILEVER","LOCAL VENDORS-B","0","0",],
            ["SHAHEEN TRADERS MEIJI","LOCAL VENDORS-B","0","0",],
            ["KR&F DISTRIBUTOR FINIS","LOCAL VENDORS-B","0","0",],
            ["AHMAD ENTERPRICES CROCKERY(PSB)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["BIN BAKAR PERFUMES","SHAH ALAM VENDOR -C","0","0",],
            ["INSAAF MARKETING","LOCAL VENDORS-B","0","0",],
            ["ALLIED MARKETING (KOLESTON COLOR)","LOCAL VENDOR-C","0","0",],
            ["FIVE STAR TRADE (DARCO) PREV PRIME MARKETING","LOCAL VENDORS-B","0","0",],
            ["ZEESHAN TRADERS (PARTY+BIRTHDAY)","LOCAL VENDOR-C","0","0",],
            ["ABDULLAH TRADERS (MILLAC BUTTER)","LOCAL VENDORS-B","0","0",],
            ["ZIA SONS (STILLMANS)","LOCAL VENDOR-C","0","0",],
            ["PARAZELSUS PAKISTAN (PVT) RECKIT","LOCAL VENDORS-B","0","0",],
            ["URBAN TRENDS ","LOCAL VENDORS-B","0","0",],
            ["AL-SYED TRADERS-2 (BISCONNI)","LOCAL VENDORS-B","0","0",],
            ["WALI & CO (PEAK FREANS)","LOCAL VENDORS-B","0","0",],
            ["OPAL DISTRIBUTOR (PVT).LTD KIWI","LOCAL VENDORS-B","0","0",],
            ["NAWAZ BROTHERS (LAYS)","LOCAL VENDORS-B","0","0",],
            ["MOHD JAMIL ABDUL WAHEED & CO (FAUJI)","LOCAL VENDORS-B","0","0",],
            ["ANR TRADERS (RISEN TISSUES)","LOCAL VENDOR-C","0","0",],
            ["AL-RAHEEM MARKETING (GUARD RICE)","LOCAL VENDORS-B","0","0",],
            ["SR TRADERS MITCHELLS ","LOCAL VENDORS-B","0","0",],
            ["MAJEED & SONS (SHEZAN)","LOCAL VENDORS-B","0","0",],
            ["JS MARKETING (BOLD BODY SPRAY)","LOCAL VENDORS-B","0","0",],
            ["NPD PVT LIMITED (BISCONI)","LOCAL VENDORS-B","0","0",],
            ["AL MUSLIM DISTRIBUTORS (HILAL)","LOCAL VENDOR-C","0","0",],
            ["AM TRADERS (INOVATIVE)","LOCAL VENDOR-C","0","0",],
            ["M&F ENTERPRISES (CANDY LAND)","LOCAL VENDOR-C","0","0",],
            ["MAK FOOD PAKISTAN (DRY FRUIT)","LOCAL VENDOR-C","0","0",],
            ["SEASONS EDIBLE OIL LIMITED","LOCAL VENDORS-B","0","0",],
            ["AYYAN TRADERS (DASTAK BANASPATI)","LOCAL VENDOR-C","0","0",],
            ["REHAN & SONS EMBORG","LOCAL VENDOR-C","0","0",],
            ["AL RAHEEM TRADERS (SOFT TOUCH)","LOCAL VENDOR-C","0","0",],
            ["LADIES UNDERGARMENTS","LOCAL VENDOR-C","0","0",],
            ["UNI SWIFT TRADER (FOOT BALL)","LOCAL VENDOR-C","0","0",],
            ["GARMENTS VENDOR(NEW)","OUTSOURCED VENDOR","0","0",],
            ["K.K TRADERS (CANOLIVE)","LOCAL VENDORS-B","0","0",],
            ["TRADE INTERNATIONAL (DISPOSIABLE) PREV UNIQUE CORPORATION ","LOCAL VENDORS-B","0","0",],
            ["HALEEB FOODS (BUTTER)","LOCAL VENDOR-C","0","0",],
            ["NEW NEST DISTRIBUTORS (PAKOLA)","LOCAL VENDORS-B","0","0",],
            ["MADNI TRADERS (SHAHALAM)","SHAH ALAM VENDOR-B","0","0",],
            ["SAIGOL INTERNATIONAL (FORMULA 1)","LOCAL VENDOR-C","0","0",],
            ["HASHIM ENTERPRISES (MARIOS)","LOCAL VENDORS-B","0","0",],
            ["WALI & SONS (MARIOS)","LOCAL VENDORS-B","0","0",],
            ["BE HAPPY PETS (PVT) LIMITED CAT FOOD","LOCAL VENDOR-C","0","0",],
            ["USMAN BROTHERS (PVT) LTD LOACKER","LOCAL VENDORS-B","0","0",],
            ["SIA BEVERAGES COCA COLA","LOCAL VENDORS-B","0","0",],
            ["ZAHRA TRADERS FLOWER ","LOCAL VENDOR-C","0","0",],
            ["PUNJAB DAIRY ","LOCAL VENDORS-B","0","0",],
            ["ALL SEASON FROZEN ","LOCAL VENDOR-C","0","0",],
            ["A.M ENTERPRISES (THAI COLLECTION)","SHAH ALAM VENDOR-B","0","0",],
            ["MALIK INTERNATIONAL TRADERS (BABY ZONE)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["GLOBAL BRANDS MARKETING (PVT) LTD MEIJI","LOCAL VENDOR-C","0","0",],
            ["ITC GROP LOLANE ","LOCAL VENDOR-C","0","0",],
            ["J.B EGG TRADERS ","LOCAL VENDOR-C","0","0",],
            ["NUTRILOV GRANOLA BARS ","LOCAL VENDOR-C","0","0",],
            ["PRINCE ASSOCIATE COLGATE ","LOCAL VENDORS-B","0","0",],
            ["A & SONS LAHORE (SHANGRILA)","LOCAL VENDORS-B","0","0",],
            ["MAQSOOD TRADING SERVICES (CANBEBE) PREV SPOT DISTRIBUTION","LOCAL VENDORS-B","0","0",],
            ["MULLER & PHIPPS (BLUE BAND)","LOCAL VENDORS-B","0","0",],
            ["KHALIS GHEE (DESI GHEE) PREV KISAN TRADERS ","LOCAL VENDORS-B","0","0",],
            ["ELITE BRANDS LIMITED (OLPERS)","LOCAL VENDORS-B","0","0",],
            ["B GROWTHS (SUFI DETERGENT)","LOCAL VENDORS-B","0","0",],
            ["CONCEPT PAPER PRODUCTS ","LOCAL VENDOR-C","0","0",],
            ["MUSA TRADERS (ZARAFA RICE)","LOCAL VENDOR-C","0","0",],
            ["ALBARKA ENTERPRISES (HASAN RICE)","LOCAL VENDOR-C","0","0",],
            ["AWAIS TRADERS (MARHABA)","LOCAL VENDORS-B","0","0",],
            ["ELITE BRANDS LIMITED (HILAL)","LOCAL VENDORS-B","0","0",],
            ["BISMILLAH TRADERS ","LOCAL VENDOR-C","0","0",],
            ["CHANNEL LINK (MARIO,S)","LOCAL VENDOR-C","0","0",],
            ["MAKKI TRADERS (HALEEB) PREV SS MARKETING","LOCAL VENDORS-B","0","0",],
            ["ARTIFICIAL JEWELLERY VENDOR","OUTSOURCED VENDOR","0","0",],
            ["REHMANIA INTERNATIONAL (EVELINE) PREV SABRI ENTERPRISES","LOCAL VENDORS-B","0","0",],
            ["EMADULLAH DISTRIBUTORS(CANBEBE)","LOCAL VENDORS-B","0","0",],
            ["RANA JAHANGIR TRADERS (NURPUR)","LOCAL VENDOR-C","0","0",],
            ["RAFI TRADERS PREV THE TOYS","LOCAL VENDORS-B","0","0",],
            ["BHOLAWALA AGENCIES(FAALIN-PIGEON)","LOCAL VENDOR-C","0","0",],
            ["NUR ENTERPRISES (BUTTERFLY)","LOCAL VENDORS-B","0","0",],
            ["AL RAHMAN TRADING COMPANY (MEZAN OIL/TEA)","LOCAL VENDORS-B","0","0",],
            ["K & B TRADERS (MILLAC) PREV MUSA TRADERS ","LOCAL VENDORS-B","0","0",],
            ["BURQUE CORPORATION (PVT) LTD FINE TISSUES","LOCAL VENDORS-B","0","0",],
            ["ASAD TRADERS (BREEO)","LOCAL VENDOR-C","0","0",],
            ["TALHA TRADERS HABIB OIL ","LOCAL VENDORS-B","0","0",],
            ["IMTIAZ GENERAL MERCHANT SHAHALAM","SHAH ALAM VENDOR -C","0","0",],
            ["NAWABgANIC","LOCAL VENDORS-B","0","0",],
            ["AL-SADEED TRADERS (BISCONNI) PREV ESA TRADERS","LOCAL VENDORS-B","0","0",],
            ["QUALITY PET,S (PET FOOD)","LOCAL VENDOR-C","0","0",],
            ["HU TRADERS (ROOH AFZA)","LOCAL VENDORS-B","0","0",],
            ["HAJI SAAB (HOUSEHOLD+GARMENTS)","LOCAL VENDOR-C","0","0",],
            ["F & N ENTERPRISES (RAWALPINDI)","SHAH ALAM VENDOR -C","0","0",],
            ["ALI COMMERCIAL CORPORATION (RICE)","LOCAL VENDORS-B","0","0",],
            ["SIGMA DISTRIBUTORS PVT LIMITED (RED BULL)","LOCAL VENDORS-B","0","0",],
            ["NATURE STORIES (HONEY)","LOCAL VENDORS-B","0","0",],
            ["HASHIM DRY FRUIT MIX ","OUTSOURCED VENDOR","0","0",],
            ["RAZI SONS (YC& FIABILA)","LOCAL VENDOR-C","0","0",],
            ["AHMED BILAL TRADER (AL RAZA RICE) PREV S & A BROTHERS","LOCAL VENDORS-B","0","0",],
            ["SHOPPING BAGS ","LOCAL VENDORS-B","0","0",],
            ["BADAR AL JAZEERA ((SUNRIDGE FLOUR))","LOCAL VENDORS-B","0","0",],
            ["GENERAL STATIONARY ITEM ","LOCAL VENDOR-C","0","0",],
            ["SHAHAN DISTRIBUTOR (AL MARAI)","LOCAL VENDOR-C","0","0",],
            ["BILAL ENTERPRISES (ILYAS FANCY)","SHAH ALAM VENDOR-B","0","0",],
            ["THE CELEBRATION COMPANIONS","LOCAL VENDORS-B","0","0",],
            ["WALI ALI TRADING COMPANY ","LOCAL VENDOR-C","0","0",],
            ["BAO JAVED ELECTRONICS ","LOCAL VENDOR-C","0","0",],
            ["NAIMAT ENTERPRISES (KITCHEN KING)","LOCAL VENDORS-B","0","0",],
            ["A A TRADER (ARIQ INTERNATIONAL)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["TALAL AND COMPANY (ROSSMORE) PREV AMIR TRADING ","LOCAL VENDORS-B","0","0",],
            ["ABBAS TRADERS (SALMAN JAM) ","LOCAL VENDORS-B","0","0",],
            ["REAL FOOD PRIVATE LIMITED (OREAL)","LOCAL VENDORS-B","0","0",],
            ["IMRAN TRADERS (HOME DECORE CHEQUE)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["MAKSON TRADERS LMT (SUNRIDGE ATTA)","LOCAL VENDORS-B","0","0",],
            ["CHANNEL LINK (CANDYLAND)","LOCAL VENDORS-B","0","0",],
            ["BAHOO TRADERS (MOTHERCARE)","LOCAL VENDORS-B","0","0",],
            ["GLITZ SERVICES (PVT) LIMITED (BREEO)","LOCAL VENDORS-B","0","0",],
            ["OPTIMUS CREST (PVT) LTD (MARIO PASTA)","LOCAL VENDORS-B","0","0",],
            ["ANJUM ASIF & CO. (COROLI)","LOCAL VENDORS-B","0","0",],
            ["FARSHA TRADERS(BABY LAND SHAHLAM)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["HAMEED & CO (BABY LAND SHAHLAM)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["HB & CO. PREV SALEEM & SONS (AL FATAH TOYS SHAHLAM)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["NAGINA TRADERS(HOME DECORE SHAHLAM)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["TOY CENTRE (HAMMAD TOYS SHAHLAM)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["COLGATE-PALMOLIVE (PAKISTAN) LTD.","LOCAL VENDORS-B","0","0",],
            ["R,A TRADERS (SAMSOL)","LOCAL VENDORS-B","0","0",],
            ["Z M ENTERPRISES (AK PHENYLE)","LOCAL VENDOR-C","0","0",],
            ["THE TRADING TRACK (AMERICANA KUISINE)","LOCAL VENDORS-B","0","0",],
            ["OSAF TRADER (DESI GHEE)","LOCAL VENDOR-C","0","0",],
            ["UNITED BRANDS LIMITIED (MEDJOHNSONS)","LOCAL VENDORS-B","0","0",],
            ["ZAKA TRADERS (SAEED GHANI) PREV WARIS WALI TRADER ","LOCAL VENDOR-C","0","0",],
            ["MR.CANDY (LOLIPOP)","LOCAL VENDOR-C","0","0",],
            ["DANY TECHNOLOGY (AUDIONIC)","LOCAL VENDORS-B","0","0",],
            ["AA TRADERS (ARIQ INTERNATIONAL)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["FAIR MARKETING (NANDOS)","LOCAL VENDORS-B","0","0",],
            ["MUZAMMIL BROTHERS(SUFI OIL&GHEE)","LOCAL VENDORS-B","0","0",],
            ["IKHLAS TRADERS(ZARAFA RICE)","LOCAL VENDORS-B","0","0",],
            ["MULLER & PHIPPS (UNILEVER)","LOCAL VENDORS-B","0","0",],
            ["QARSHI INDUSTRIES PVT LTD.","LOCAL VENDORS-B","0","0",],
            ["SAFA INTERNATIONAL (KILITE CHEMICALS)","LOCAL VENDOR-C","0","0",],
            ["NEAT FOODS PVT LTD. (O.FOOS)","LOCAL VENDORS-B","0","0",],
            ["GREEN WAY MARKETING (NURPUR)","LOCAL VENDOR-C","0","0",],
            ["EFF DEE WATER (WISTO CHEESE) PREV ZSJ ENTERPRISES","LOCAL VENDORS-B","0","0",],
            ["MZ ENTERPRISES (BARBICAN)","LOCAL VENDOR-C","0","0",],
            ["BISMA TRADERS (CANOLIVE)","LOCAL VENDORS-B","0","0",],
            ["AZ MARKETING ","LOCAL VENDORS-B","0","0",],
            ["BURQUE CORPORATION (PVT)LTD RECKIT ","LOCAL VENDORS-B","0","0",],
            ["JAJA GLOBAL ","SHAH ALAM VENDOR -C","0","0",],
            ["IM TRADERS SHAHLAM","SHAH ALAM VENDOR -C","0","0",],
            ["JS TRADER TRADERS LAHORE SHAHLAM","SHAH ALAM VENDOR -C","0","0",],
            ["FAISAL & SONS (CROCKERY)","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["THE SALT COMPANY","LOCAL VENDOR-C","0","0",],
            ["FJS ENTERPRISER (LAYS)","LOCAL VENDORS-B","0","0",],
            ["KAAF TRADER (PEEK FREANS)","LOCAL VENDORS-B","0","0",],
            ["AL KHAIR TRADERS (COLGATE)","LOCAL VENDORS-B","0","0",],
            ["CAPCON ENTERPRISES LAHORE (YOUNGS)","LOCAL VENDORS-B","0","0",],
            ["RAFIQ TRADER (LONDON)","LOCAL VENDORS-B","0","0",],
            ["MALIK HASSAN TRADERS (EDEN ROC)","LOCAL VENDOR-C","0","0",],
            ["CHAUDHRY TRADERS (SUNRIDGE ATTA)","LOCAL VENDORS-B","0","0",],
            ["ZAHID BROTHERS (BAKE PARLOR)","LOCAL VENDOR-C","0","0",],
            ["AIANA INTERNATIONAL (GENNY) PREV MSG LAHORE","LOCAL VENDOR-C","0","0",],
            ["AAA MARKETING SERVICE ","LOCAL VENDOR-C","0","0",],
            ["GHAZI INDUSTRY (SHAHLAM) PREV IMPERIAL STEEL & CROCKERY HOUSE ","SHAH ALAM VENDOR- CROCKERY AND OTHERS","0","0",],
            ["DELI KC FOOD ","LOCAL VENDOR-C","0","0",],
            ["ANEX ELECTRONICS","SHAH ALAM VENDOR -C","0","0",],
            ["RAZZAQIA TOWEL CENTER","LOCAL VENDOR-C","0","0",],
            ["MOANA AZUL (SHAHALAM TOYS)","SHAH ALAM VENDOR-B","0","0",],
            ["PREMIER SALES (UNILEVER)","LOCAL VENDORS-B","0","0",],
            ["UNITED BRANDS (CANDYLAND)","LOCAL VENDORS-B","0","0",],
            ["ALPHA ENTERPRISES (STILLMAN)","LOCAL VENDORS-B","0","0",],
            ["EMADULLAH AND BROTHERS (GOLDEN PEARL) PREV AL-MUSLIM DISTRIBUTORS","LOCAL VENDORS-B","0","0",],
            ["CH. BROTHERS (COLGATE-PALMOLIVE)","LOCAL VENDORS-B","0","0",],
            ["HEMANI HERBAL","LOCAL VENDORS-B","0","0",],
            ["OPTIMUS CREST (OLPERS CHEESE)","LOCAL VENDOR-C","0","0",],
            ["GLOBAL TRADERS (SHAH ALAM)","SHAH ALAM VENDOR-B","0","0",],
            ["MASOOMIA TRADERS (NESTLE)","LOCAL VENDORS-B","0","0",],
            ["LIFONIC BRANDS (DEL MONTE)","LOCAL VENDORS-B","0","0",],
            ["KK SPORTS (SHAH ALAM)","SHAH ALAM VENDOR-B","0","0",],
            ["SAJID TRADNG (CO NATURAL)","LOCAL VENDORS-B","0","0",],
            ["GLOBAL ROYAL TRADING (HOLSTEN)","LOCAL VENDORS-B","0","0",],
            ["A.R TRADERS (HEMANI PERFUME)","LOCAL VENDORS-B","0","0",],
            ["BASIT TRADERS","SHAH ALAM VENDOR-B","0","0",],
            ["AHMED TRADERS (COSMETICS)","SHAH ALAM VENDOR -C","0","0",],
            ["MALIK FRAMING (SHAHALAM)","SHAH ALAM VENDOR -C","0","0",],
            ["GS INTERNATIONAL","LOCAL VENDOR-C","0","0",],
            ["CHOUDHRY BROTHERS (WRIST WATCHES)","SHAH ALAM VENDOR-B","0","0",],
            ["AZ HOUZERY (SHAH ALM)","SHAH ALAM VENDOR-B","0","0",],
            ["EMADULLAH & BROTHERS (KINGTOX)","LOCAL VENDORS-B","0","0",],
            ["AL-WADI POULTRY FORM (EGGS)","LOCAL VENDOR-C","0","0",],
            ["MULTI LINE NETWORK (SHAH ALAM)","SHAH ALAM VENDOR -C","0","0",],
            ["RIOS (YARDELY, ENCHANTER)","SHAH ALAM VENDOR -C","0","0",],
            ["A & Z AGRO (SHAFQ GEE & OIL)","LOCAL VENDORS-B","0","0",],
            ["ASHRAFI TRADERS (CARESS)","LOCAL VENDORS-B","0","0",],

        ];
        $uuid = 16729820182137;
        $i = 1;
        $p = 2;
        foreach ($data as $row){

            $name = trim(strtolower(strtoupper($row[0])));
            if(!\App\Models\TblPurcSupplier::where(\Illuminate\Support\Facades\DB::raw("lower('supplier_name')"),$name)->exists()){
                $supplier_type_name = trim(strtolower(strtoupper($row[1])));
                $supplier_type = null;
                if(!\App\Models\TblPurcSupplierType::where(\Illuminate\Support\Facades\DB::raw("lower(supplier_type_name)"),$supplier_type_name)->exists()){
                    $supplier_type = \App\Models\TblPurcSupplierType::where(\Illuminate\Support\Facades\DB::raw("lower(supplier_type_name)"),$supplier_type_name)->first();
                }

                \App\Models\TblPurcSupplier::create([
                    'supplier_id' => $uuid,
                    'supplier_code' => 'SP-'.sprintf("%'07d", $p),
                    'supplier_name' => $row,
                    'supplier_type' => isset($supplier_type->supplier_type_id)?$supplier_type->supplier_type_id:"",
                    'supplier_credit_period' => empty($row[2])?0:$row[2],
                    'supplier_credit_limit' => empty($row[3])?0:$row[3],
                    'supplier_entry_status' => 1,
                    'supplier_user_id' => 81,
                    'business_id' => 1,
                    'company_id' => 1,
                    'branch_id' => 1,
                ]);
                $uuid = $uuid + $i ;
                $p = $p + 1;
                $i = $i + 1;
            }
        }





        /* chart account  */

        $data = App\Models\TblPurcSupplier::select('supplier_id')->get();
        $i = 0;
        foreach ($data as $item){
            // dd($item);
            $modalData = App\Models\TblPurcSupplier::where('supplier_id',$item->supplier_id)->first();
            $supplierType = App\Models\TblPurcSupplierType::where('supplier_type_id',$modalData->supplier_type)->first();
            $chart = App\Models\TblAccCoa::where('chart_account_id',$supplierType->supplier_type_account_id)->first();

            $parent_account_code = $chart->chart_code;
            $level_no = 4;
            $business_id = 1;
            $company_id = 1;
            $branch_id = 1;
            $user_id = 81;
            $chart_name = $modalData->supplier_name;

            $pdo = Illuminate\Support\Facades\DB::getPdo();
            $account_id = 0;
            $stmt = $pdo->prepare("begin ".Utilities::getDatabaseUsername().".PRO_PURC_CHART_INSERT(:p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8); end;");
            $stmt->bindParam(':p1', $level_no);
            $stmt->bindParam(':p2', $parent_account_code);
            $stmt->bindParam(':p3', $business_id);
            $stmt->bindParam(':p4', $company_id);
            $stmt->bindParam(':p5', $branch_id);
            $stmt->bindParam(':p6', $user_id);
            $stmt->bindParam(':p7', $chart_name);
            $stmt->bindParam(':p8', $account_id,\PDO::PARAM_INT);
            $stmt->execute();

            $modalData->supplier_account_id = $account_id;
            $modalData->save();

            $i += 1;
            echo $i .' - ';
        }
    }
}
