-- ---------------------------------------------------------------------------
-- DDL for table ACTIVITY_LOGS (Oracle Database / TOAD for Oracle)
-- ---------------------------------------------------------------------------

CREATE TABLE activity_logs (
    id              NUMBER(19)        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    business_id     NUMBER(10)        NOT NULL,
    user_id         VARCHAR2(64)      NULL,
    branch_id       NUMBER(10)        NULL,
    device_id       VARCHAR2(128)     NULL,
    app_version     VARCHAR2(32)      NULL,
    platform        VARCHAR2(16)      NULL,
    client_log_id   NUMBER(19)        NOT NULL,
    log_type        VARCHAR2(40)      NOT NULL,
    category        VARCHAR2(80)      NULL,
    source          VARCHAR2(255)     NULL,
    message         VARCHAR2(4000)    NULL,
    error_details   CLOB              NULL,
    stack_trace     CLOB              NULL,
    status_code     NUMBER(5)         NULL,
    extra_data      CLOB              NULL,
    event_at        TIMESTAMP(3)      NOT NULL,
    received_at     TIMESTAMP(3)      DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Primary Key
ALTER TABLE activity_logs
    ADD CONSTRAINT pk_activity_logs PRIMARY KEY (id);

-- Deduplication Unique Key on (user_id, device_id, client_log_id)
ALTER TABLE activity_logs
    ADD CONSTRAINT uq_activity_logs_dedup UNIQUE (user_id, device_id, client_log_id);

-- Performance Indexes
CREATE INDEX ix_activity_logs_user     ON activity_logs (user_id);
CREATE INDEX ix_activity_logs_branch   ON activity_logs (branch_id);
CREATE INDEX ix_activity_logs_type     ON activity_logs (log_type);
CREATE INDEX ix_activity_logs_event_at ON activity_logs (event_at);

-- Table & Column Comments
COMMENT ON TABLE activity_logs IS 'Activity logs synced from mobile app offline/online buffer';
COMMENT ON COLUMN activity_logs.id IS 'Primary Key auto-generated sequence/identity';
COMMENT ON COLUMN activity_logs.business_id IS 'Business ID from token/user session';
COMMENT ON COLUMN activity_logs.client_log_id IS 'Local SQLite row ID from mobile client';
COMMENT ON COLUMN activity_logs.event_at IS 'UTC timestamp when event occurred on client device';
COMMENT ON COLUMN activity_logs.received_at IS 'Timestamp when server received the log';
