-- ---------------------------------------------------------------------------
-- DDL for table ORDER_RECIPE_USAGES
-- ---------------------------------------------------------------------------

CREATE TABLE order_recipe_usages (
    id                   NUMBER(19)        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    order_id             NUMBER(19)        NOT NULL,
    order_detail_id      NUMBER(19)        NOT NULL,
    restaurant_id        NUMBER(19)        NOT NULL,
    food_id              NUMBER(19)        NOT NULL,
    option_list_id       NUMBER(19)        NOT NULL,
    food_recipe_id       NUMBER(19)        NOT NULL,
    product_id           NUMBER(19)        NOT NULL,
    product_quantity     NUMBER(15, 4)     NOT NULL,
    measure_unit         VARCHAR2(50 CHAR) NULL,
    usage_date           DATE              NOT NULL,
    created_at           TIMESTAMP(6)      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at           TIMESTAMP(6)      DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Primary key
ALTER TABLE order_recipe_usages
    ADD CONSTRAINT pk_order_recipe_usages PRIMARY KEY (id);

-- Natural key to prevent duplicates per order detail and product
ALTER TABLE order_recipe_usages
    ADD CONSTRAINT uq_order_recipe_usage UNIQUE (order_detail_id, product_id);

-- Foreign key placeholders (uncomment when referenced tables have PKs exposed)
-- ALTER TABLE order_recipe_usages ADD CONSTRAINT fk_oru_order
--     FOREIGN KEY (order_id) REFERENCES orders (id);
-- ALTER TABLE order_recipe_usages ADD CONSTRAINT fk_oru_order_detail
--     FOREIGN KEY (order_detail_id) REFERENCES order_details (id);
-- ALTER TABLE order_recipe_usages ADD CONSTRAINT fk_oru_food_recipe
--     FOREIGN KEY (food_recipe_id) REFERENCES food_recipes (id);
-- ALTER TABLE order_recipe_usages ADD CONSTRAINT fk_oru_food_product
--     FOREIGN KEY (product_id) REFERENCES foods (id);

-- Supporting indexes for filtering by restaurant/date/product
CREATE INDEX ix_oru_restaurant_date ON order_recipe_usages (restaurant_id, usage_date);
CREATE INDEX ix_oru_option_list ON order_recipe_usages (option_list_id);
CREATE INDEX ix_oru_product ON order_recipe_usages (product_id);

-- Trigger to keep updated_at in sync with modifications
CREATE OR REPLACE TRIGGER trg_oru_updated_at
    BEFORE UPDATE ON order_recipe_usages
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/


